/***************************************************************************************************************************
 * Name:        ASI_CRM_SG_Voucher_Page_Test
 * Description: Test class for ASI_CRM_SG_Voucher_Page_Ctrl
 *
 * Version History
 * Date             Developer               Comments
 * ---------------  --------------------    --------------------------------------------------------------------------------
 * 2018-05-15       Jeffrey Cheung          Created
 ****************************************************************************************************************************/

@IsTest
private class ASI_CRM_SG_Voucher_Page_Test {
    @IsTest static void testBehavior() {
        ASI_CRM_SG_Voucher_Page_Ctrl controller = new ASI_CRM_SG_Voucher_Page_Ctrl();
    }
}