/********************************************************************************
*                         Copyright 2012 - Cloud2b
********************************************************************************
* Controller da pagina 
* NAME: EditaVisitasController.cls
* AUTHOR: ROGÉRIO ALVARENGA                       DATE: 
*
*
* MAINTENANCE: INSERIDO LÓGICA DE VALIDAÇÃO DO TIPO DE REGISTRO DOS OBJETOS.
* AUTHOR: CARLOS CARVALHO                         DATE: 14/01/2013 
********************************************************************************/
public class EditaVisitasController {
      /*
      public static List<Visitas__c> getVisitas() {
          Id idRecTypeVis = RecordTypeForTest.getRecType( 'Visitas__c', 'BRA_Standard' );
          
          return [ SELECT Id, Conta__c, Data_da_Visita__c,Hora_da_Visita__c,Planejamento__c,Resumo_da_Visita__c, Semana__c
              FROM Visitas__c WHERE RecordTypeId =: idRecTypeVis ];
      }
      */
}