<div style="background-color:#FFFFFF;">
<p align="center">
<b>PERNOD RICARD<br/>
USE OF THE ENTERPRISE SOCIAL NETWORK POLICY<br/>
("ESN POLICY")</b>
<br/><br/><br/>
</p>
<b>1. Why a Policy?</b>
<p>The Pernod Ricard S.A. company and its affiliates (hereafter "<b>Pernod Ricard</b>") recognize the vital importance of social media to develop the Pernod Ricard social vision of a wider social interaction to connect and empower users by "sharing a new idea every day". Pernod Ricard has thus launched an Enterprise Social Network (hereafter the "<b>ESN</b>") called "<b>Pernod Ricard Chatter&reg;</b>" accessible by users as defined below in this policy.</p>
<p>This ESN allows users, to chat/exchange information interactively, rapidly and in a user-friendly manner.</p>
<p>The growth of the volume of information exchanged via Pernod Ricard Chatter&reg; together with the fast way in which such information is spread out calls for a reminder of the principles and rules of conduct governing the usage of Pernod Ricard Chatter&reg;.</p>
<p>This ESN policy (hereafter the "<b>ESN Policy</b>") is intended to outline:<br/>
<ul><li> how the values and legal principles of Pernod Ricard should be respected and demonstrated when using the ESN Policy and to guide the participation of users in this area both when users participate personally, as well as when acting on behalf Pernod Ricard making them aware of the risks arising from such use. It is critical that we always remember who we are and what our role is in the social media community to build our brands. The same rules that apply to our messaging and communications in traditional media as set forth in the IT policies of Pernod Ricard still apply in the online social media space;</li>
<li> to inform users in accordance with applicable data privacy laws on the conditions in which their personal information are processed when they use the ESN. "<b>Personal Information</b>" means any information that enables the identification of a person, whether directly or indirectly, such as an identification number, or one or more factors specific to his physical, physiological, mental, economic, cultural or social identity (e.g. name, address, photo, voice etc.).</li></ul></p>

<b>2. What is the scope of the Policy?</b>
The ESN Policy is applicable to:
 <ul><li>all Pernod Ricard employees worldwide (hereafter the "<b>Employees Users</b>"); and</li>
 <li>any user invited to use Pernod Ricard Chatter&reg; by a Pernod Ricard employee and bound to Pernod Ricard by a contract to which the ESN Policy is attached (hereafter the "<b>External Users</b>).</li></ul>
<p>Both categories of users are defined as the "<b>Users</b>".</p>
<p>The ESN Policy supplements the "IT Policy" of the Pernod Ricard company ("Charte technologique") which governs the use of the IT resources including the ESN made available by the Pernod Ricard company, and is part of the Internal Regulations ("R&eacute;glement Int&eacute;rieur"). This Policy also supplements the IT policies of the affiliates within Pernod Ricard, when applicable.</p>

<b>3. How to accept the ESN Policy terms?</b>
<p>When he/she will first log in to the ESN, the User will have to double click on the acceptance button "I agree" displayed on the screen after having read the ESN Policy, to express his/her consent.</p>

<b>4. How are Users personal information processed when using the ESN?</b>
<p>Pernod Ricard processes Users Personal Information fairly and in accordance with applicable laws.</p>
<p>In addition to the basic Personal Information (such as name, first name, e-mail address, telephone number, job title, etc..) collected either directly (e.g. collection form to be used by External Users to be approved as User) or indirectly (e.g. existing Pernod Ricard / Group Directory for Employees Users) from the Users, Users may also decide to include other types of information, including status, comments, "likes", documents, content and pictures, on a voluntary basis, subject to the general conditions of use of this ESN Policy. Such information may also contain Personal Information about the Users. Other information may also be collected on Users usage of the ESN for monitoring purposes as set forth in article 9 of the ESN Policy.</p>
<p>Users are informed that:</p>
<ul><li>their personal information are processed by Pernod Ricard <b>for the sole purpose</b> of the ESN functioning to help develop and improve ways of working together online (increase knowledge sharing, enable greater collaboration, enable better sharing of best practices, foster greater innovation, enable wider social interaction, reinforce entrepreneurship, boost innovation, etc.).</li>
<li>the <b>categories of recipients</b> which will access their Personal Information are (i) all Users. Said Users may be Employees or External Users located in the European Union or outside the European Union, (ii) the service providers used by Pernod Ricard to support the ESN and (iii) Pernod Ricard's administrators and community managers who may be employees of the Pernod Ricard company or its affiliates.</li></ul>

<p>To help Pernod Ricard maintaining the accuracy of the Users Personal Information, Users are entitled to access the Personal Information held about them, to have inaccurate Personal Information corrected or removed or to object to the processing of their Personal Information, except where the data processing is implemented in compliance with mandatory provisions of French law. Such rights may only be exercised for legitimate purposes and should not be abusive.</p>
<p>For that purpose, Users are given the option to update certain of their Personal Information directly on their profile page.</p>
<p>For the Personal Information which may not be accessed directly online by the Users, the Users can exercise their can exercise their <b>right of access and rectification</b> of their Personal Information by sending an email to the following address: chatter@pernod-ricard.com. The Pernod Ricard company will respond to Users request within a reasonable time.</p>
<p>Pernod Ricard maintains reasonable technical and organizational <b>security measures</b> to protect Personal Information against accidental or unlawful alteration or loss, or from unauthorized use, disclosure or access, in compliance with applicable law.</p>
<p>Pernod Ricard will store Personal Information for no longer than necessary to carry out the purposes described in this ESN Policy. Such personal information will then be archived in accordance with applicable law.</p>

<b>5. How may Users Personal Information be subject to International transfers?</b>
<p>Given that Pernod Ricard is an international group and because the ESN is per se a tool which is used by Users worldwide, the Personal Information processed via the ESN will be transferred to all the countries where the Users of a given community are based, i.e. in all the countries where Pernod Ricard has offices, and to the countries where the authorised External Users or third party providers used in relation with the operation of the ESN are located. The list of countries where Personal Information will be transferred is attached hereto as Annex.</p>
<p>The data recipients may be located outside of the European Economic Area, in countries which may not offer a level of adequate protection as European countries or countries recognised as granting an equivalent level of data protection.</p>

<p>To secure the international transfers of data which may result from an access of all the data recipients listed above to the Personal Information processed through the ESN, Pernod Ricard has implemented appropriate contractual measures, based on the model clauses of the European Commission, to establish and/or confirm that, prior to receiving any Personal Information, the data recipient located in such countries will process the data with an adequate level of protection and that appropriate technical and organizational security measures are in place to protect Personal Information against accidental or unlawful destruction or accidental loss, alteration, unauthorized disclosure or access, and against all other unlawful forms of processing.</p>
<p>Users are further informed that the service provider used to support the ESN platform and located in the USA, has been granted a Safe Harbor certification which is generally recognized by Data Protection Authorities as granting an adequate protection for data flows from European Users to said service provider. If such protection is not considered as sufficient by the Data Protection Authority of a User's country, Pernod Ricard will implement appropriate contractual measures based on the model clauses of the European Commission.</p>

<b>6. What are the general principles which must be respected by Users when interacting on the ESN?</b>
<p>Some essential obligations incumbent on the Users under their respective contract with Pernod Ricard, and especially their duty of confidentiality, are extended to their communication via the ESN.</p>
<p>It is therefore important that all Users make sure they conduct themselves on the ESN in a responsible manner, exercising discretion and common sense. Each User shall bear in mind the fact that any content posted on the ESN is visible by all other Users or Users of specific communities.</p>
<p>While interacting on the ESN, the User understands that he/she may be in sustained contact with Employee Users or External Users not directly involved in his/her assigned missions and that he/she may be provided with access to sensitive, confidential information such as for example sales, marketing, human resources, financial or legal information (hereafter the "Confidential Information").</p>
<p>In particular, in addition to confidentiality agreements that Users may have entered into with Pernod Ricard, Users agree:</p>
<ul><li style="list-style-type: none;">(i) To use the Confidential Information only as follows:</li>
<ul><li>use Confidential Information in a manner consistent only in furtherance of Users' assigned roles and responsibilities within or for Pernod Ricard;</li>
<li>take all reasonable measures to avoid disclosure, dissemination, or unauthorized use of Confidential Information and report any unauthorized disclosure to the Employee User's manager, legal or human resources services.</li>
<li>not to access, without prior authorization, professional information or computing resources owned by the other Users of the ESN and/or which are not in the assigned duties and responsibilities of the User;</li>
<li>not to modify or destroy any information other than that necessary to perform the assigned duties and responsibilities of the User.</li></ul>
<li style="list-style-type: none;">(ii) Not to denigrate Pernod Ricard or its competitors, nor make denigrating or defamatory remarks about working relationships.</li>
<li style="list-style-type: none;">(iii) Behave responsibly and respectfully towards Pernod Ricard and other third parties and act as an ambassador of Pernod Ricard on the ESN, and therefore:</li>
<ul><li>not to post any content consisting in negative or harassing remarks or cause or attempts to cause any damage to the ESN or to its members;</li>
<li>not to post any comment regarding Pernod Ricard which is not truthful and respectful to Pernod Ricard, its employees, customers, partners, competitors or any other member of the ESN;</li>
<li>not to post any disparaging, discriminatory or harassing remark regarding any shareholder of Pernod Ricard, its employees, customers, partners, competitors or any other member of the ESN;</li>
<li>not to engage in any viral activity or personal data theft which may damage the ESN or negatively impacts the interest or reputation of Pernod Ricard, its employees, customers, partners, competitors or any other member of the ESN.</li></ul>
<li style="list-style-type: none;">(iv) Not to use a false identity in order to mislead others.</li>
<li style="list-style-type: none;">(v) To comply with the laws in force and to respect Pernod Ricard's employees and third parties rights and in particular the privacy and image rights of the employees of Pernod Ricard as well as third party (no posting of photos or videos of them without their consent).</li>
<li style="list-style-type: none;">(vi) Comply with the general principles of Responsible Drinking that are important to Pernod Ricard: when interacting on the ESN, the User shall always bear in mind that he or she has to comply with the Pernod Ricard responsible drinking commitments. More specifically, the User shall not post any content1 (e.g. comments, photos, videos) that:</li>
<ul><li>features any people drinking or associated with drinking who are, or who look to be, under the legal drinking age and/or encourage underage purchase or drinking of alcoholic beverages;</li>
<li>encourages illegal, irresponsible or immoderate drinking of alcoholic beverages, promotes over-consumption of alcohol or condemns or criticizes anyone who chooses not to drink alcohol;</li>
<li>portrays irresponsible drinking of alcohol in a positive light or associates drinking of alcohol with driving, operating any kind of machinery or engaging any kind of dangerous activity;</li>
<li>implies alcoholic beverages have any physical, psychological, sexual or intellectual benefits or contributes to any kind of success;</li>
<li>implies alcoholic beverages give confidence or help to overcome individual or social problems;</li>
<li>glorifies the alcohol strength, relatively high alcohol content or intoxicating effect of a drink;</li>
<li>mentions drinking alcohol in relation to any kind of illegal, antisocial, dangerous, aggressive or violent behavior or dangerous activity.</li></ul>
<li style="list-style-type: none;">(vii) To respect Pernod Ricard and third parties intellectual property rights. Consequently, each User is forbidden from reproducing and/or passing on publicly, through the ESN, any content without the authorisation of the holders of the rights relating to such content, when it is required, including all texts, logos, images, videos or audio tapes protected by Pernod Ricard or third parties intellectual property rights; Pernod Ricard particularly insists on the need to combat any act of counterfeiting and not to promote, in any way whatsoever, acts of counterfeiting which would prejudice Pernod Ricard's general commitment on the subject.</li>
<li style="list-style-type: none;">(viii) Only to pass on information the dissemination of which they consider cannot under any circumstances be prejudicial to themselves, Pernod Ricard or its employees.</li>
<li style="list-style-type: none;">(ix) To abstain from disseminating information or content that is false or misleading.</li>
<li style="list-style-type: none;">(x) Not to disseminate data, information or content of a defamatory, abusive, obscene, offensive or violent nature or inciting violence or child pornography, or of a political, racist or xenophobic nature, condoning crimes against humanity and generally any content which would be contrary to the laws and regulations in force or to public decency.</li>
<li style="list-style-type: none;">(xi) Not to collect Personal Information or data about third parties, including email addresses, to use them for commercial canvassing or for any other use, without the prior consent of the third parties involved.</li>
<li style="list-style-type: none;">(xii) To always adopt an honest, transparent and professional attitude.</li></ul><br/>
<b>7. What are the rules governing the use of ESN?</b>
<p>Use of the ESN by Users is for professional purposes.</p>
<p>Each User assumes full responsibility and liability for the statements the User shares and posts while being a member of the ESN.</p>
<p>When a User is posting content on the ESN, he/she is expressing his/her own opinion. Users are prohibited to communicate in the name and on behalf of Pernod Ricard unless they are authorized to do so by Pernod Ricard.</p>
<p>Any new community or group opened by the Employee Users and any processing of data or information or the like relating thereto, on any basis whatsoever, are the property of Pernod Ricard.</p>
<p>When the Users leave Pernod Ricard (Employee Users) or cease any business relationships with Pernod Ricard (External Users), their accounts will be closed. Any use of the login and password by the Users after they leave Pernod Ricard or cease any business relationships with Pernod Ricard in order to access their accounts is prohibited.</p>
<p>The Users also acknowledge that if the Pernod Ricard company or an affiliate within Pernod Ricard is part of a litigation in certain common law jurisdictions (e.g. the United States), all documents and contents the Users posted on Pernod Ricard Chatter&reg; may have to be disclosed during the proceedings whether these are helpful or damaging to the case.</p>
<b>8. What rules must be observed when entering into a specific user community?</b>
<p>Pernod Ricard has set up communities of users to encourage and facilitate communication between Users with a same community of interest and to better control the circulation of confidential information that should be known only to these Users, who have to know such information in respect of their activity as employees or contractors of Pernod Ricard.</p>
<p>Only Users who have access to these User communities, on account of their position in Pernod Ricard (for Employee Users) or on the basis of an express invitation from an Employee User (for External Users) may express an opinion in this regard, subject to complying with:</p>
<ul><li>The rules stated in this ESN Policy when they participate and interact with other Users;</li>
<li>The rules of restricted access to Users communities (confidentiality of access codes and not being permitted to pass them on to any unauthorised person);</li>
<li>The editorial conditions defined by the manager of each community about specific issues and subject matters.</li></ul>
<p>The opening of a new community should be made in compliance with the Naming Convention accessible in the Q&A Profile of the ESN.</p>
<b>9. How is the ESN usage monitored?</b>
<p>Users are also informed that the ESN incorporates tools which enable Pernod Ricard to monitor the Users activity on the ESN and that such monitoring activity will be conducted under the conditions set forth in this Policy, the IT Policy and the Internal Regulations for the Pernod Ricard company and the relevant IT policies of the affiliates within Pernod Ricard, when applicable.</p>
<p>Pernod Ricard reserves the right to moderate the words used on the ESN by the Users if they do not comply with this ESN Policy.</p>
<p>Users are also advised that Pernod Ricard may check breaches to this ESN Policy related to the conditions of use of its name, brand names/trademarks or information about its products or services, in order to ensure the protection and safeguarding of commercial, technical, administrative, artistic, industrial, marketing and other information belonging to Pernod Ricard.</p>
<p>Any content posted by a User on the ESN therefore incurs the User's liability for it and, if applicable, this can result in disciplinary action for Pernod Ricard Employees Users, by an immediate termination of access for External Users, if the said content does not comply with this ESN policy.</p>
<p>As part of this monitoring process, Pernod Ricard may have to:</p>
<ul><li>record a failure by Users to comply with this policy;</li>
<li>collect Personal Information of the Users who have been in breach of their obligations under this ESN policy and also collect the information in relation with the number of connexions to the ESN per day and per User. Such Personal Information processing is intended solely to be accessed by the HR departments in order to classify the breaches recorded and take a decision regarding the concerned infringing User.</li></ul><br/>
<b>10. Update</b>
<p>Should Pernod Ricard decide to modify this ESN Policy, it will issue a revised Policy and/or take other steps in accordance with applicable laws.</p>
<p>This ESN Policy was last updated on July 2, 2012.</p>
</div>