<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html><head>
	<meta http-equiv="CONTENT-TYPE" content="text/html; charset=UTF-8">
	<title></title>
	<meta name="GENERATOR" content="OpenOffice.org 3.2  (Linux)">
	<meta name="AUTHOR" content="Lesley Curtis">
	<meta name="CREATED" content="20120706;15520000">
	<meta name="CHANGEDBY" content="FAURE Marie">
	<meta name="CHANGED" content="20120706;15520000">
	<style type="text/css">
	<!--
		@page { margin-left: 1in; margin-right: 1in; margin-top: 0.2in }
		P { margin-bottom: 0.13in; direction: ltr; color: #000000; line-height: 0.18in; widows: 2; orphans: 2 margin-top: 0px;}
		P.western { font-family: "Times New Roman", serif; font-size: 10pt; so-language: en-GB }
		P.cjk { font-family: "MS Mincho"; font-size: 10pt }
		P.ctl { font-family: "Times New Roman"; font-size: 10pt }
	-->
	</style>
</head>
<body dir="LTR" lang="en-US" text="#000000">
<div type="HEADER">
	<p style="margin-bottom: 0.2in; line-height: 100%; page-break-before: always">
	<!--<img src="6bbd9_fichiers/JaVhV_html_m5ef53a75.htm" align="LEFT" border="0" height="178" width="794"><br clear="LEFT"><br>-->
	</p>
</div>
<p style="margin-bottom: 0in; line-height: 100%; widows: 0; orphans: 0" align="CENTER">
<font face="Cambria, serif"><font size="3"><font color="#1f497d"><font face="Calibri, serif"><font style="font-size: 16pt" size="4"><span lang="en-US"><b>TOP
10 Rules of the Enterprise Social Network Policy (“ESN Policy”)</b></span></font></font></font></font></font></p>
<p class="western" style="margin-bottom: 0in; line-height: 100%" align="JUSTIFY">
<font face="Cambria, serif"><font size="3"><font face="Calibri, serif">	</font></font></font></p>
<p class="western" style="margin-bottom: 0in; line-height: 100%" align="JUSTIFY">
<br>
</p>
<ol>
	<li><p style="margin-bottom: 0in; line-height: 100%" align="JUSTIFY"><font face="Cambria, serif"><font size="3"><font face="Calibri, serif"><span lang="en-US">
	Do not forget that the use of Pernod Ricard Chatter® is for
	</span></font><font face="Calibri, serif"><span lang="en-US"><b>professional
	purposes</b></span></font><font face="Calibri, serif"><span lang="en-US">.</span></font></font></font></p>
</li></ol>
<ol start="2">
	<li><p style="margin-bottom: 0in; line-height: 100%" align="JUSTIFY"><font face="Cambria, serif"><font size="3"><font face="Calibri, serif"><span lang="en-US">
	You must assume full </span></font><font face="Calibri, serif"><span lang="en-US"><b>responsibility
	and liability</b></span></font><font face="Calibri, serif"><span lang="en-US">
	for the statements you share and post on Pernod Ricard Chatter®.</span></font></font></font></p>
</li></ol>
<ol start="3">
	<li><p style="margin-bottom: 0in; line-height: 100%" align="JUSTIFY"><font face="Cambria, serif"><font size="3"><font face="Calibri, serif"><span lang="en-US">
	Bear in mind that the </span></font><font face="Calibri, serif"><span lang="en-US"><b>Pernod
	Ricard Group cannot be held liable</b></span></font><font face="Calibri, serif"><span lang="en-US">
	for the content you post on Pernod Ricard Chatter® since it only reflects your own opinion. </span></font></font></font></p>
</li></ol>
<ol start="4">
	<li><p style="margin-bottom: 0in; line-height: 100%" align="JUSTIFY"><font face="Cambria, serif"><font size="3"><font face="Calibri, serif"><span lang="en-US">
	Behave </span></font><font face="Calibri, serif"><span lang="en-US"><b>responsibly
	and respectfully</b></span></font><font face="Calibri, serif"><span lang="en-US">
	towards  the  Pernod  Ricard  Group,  its  employees, customers, partners, competitors or any other user of Pernod Ricard Chatter®. </span></font></font></font></p>
</li></ol>
<ol start="5">
	<li><p style="margin-bottom: 0in; line-height: 100%" align="JUSTIFY"><font face="Cambria, serif"><font size="3"><font face="Calibri, serif"><span lang="en-US">
	Do not </span></font><font face="Calibri, serif"><span lang="en-US"><b>denigrate</b></span></font><font face="Calibri, serif"><span lang="en-US">
	the  Pernod  Ricard  Group,  its  customers,  or  any  other  user  of  Pernod Ricard Chatter®, nor make denigrating or 
	</span></font><font face="Calibri, serif"><span lang="en-US"><b>defamatory remarks</b></span></font><font face="Calibri, serif"><span lang="en-US">
	about working relationships or our competitors.</span></font></font></font></p>
</li></ol>
<ol start="6">
	<li><p style="margin-bottom: 0in; line-height: 100%" align="JUSTIFY"><font face="Cambria, serif"><font size="3"><font face="Calibri, serif"><span lang="en-US">
	Take all reasonable measures to avoid disclosure of </span></font><font face="Calibri, serif"><span lang="en-US"><b>
	Confidential Information</b></span></font><font face="Calibri, serif"><span lang="en-US">:</span></font><font face="Calibri, serif"><span lang="en-US"><b>
	</b></span></font><font face="Calibri, serif"><span lang="en-US"> any content posted on Pernod Ricard Chatter® is visible by all users or users of specific groups. </span></font></font></font></p>
</li></ol>
<ol start="7">
	<li><p style="margin-bottom: 0in; line-height: 100%" align="JUSTIFY"><font face="Cambria, serif"><font size="3"><font face="Calibri, serif"><span lang="en-US">
	Comply with the general principles of </span></font><font face="Calibri, serif"><span lang="en-US"><b>Responsible
	Drinking</b></span></font><font face="Calibri, serif"><span lang="en-US">
	that are important to the Pernod Ricard Group.</span></font></font></font></p>
</li></ol>
<ol start="8">
	<li><p style="margin-bottom: 0in; line-height: 100%" align="JUSTIFY">
	<font face="Cambria, serif"><font size="3"><font face="Calibri, serif"><span lang="en-US">
	<b>Do not use a false identity</b></span></font><font face="Calibri, serif"><span lang="en-US">
	in order to mislead others.</span></font></font></font></p>
</li></ol>
<ol start="9">
	<li><p style="margin-bottom: 0in; line-height: 100%" align="JUSTIFY"><font face="Cambria, serif"><font size="3"><font face="Calibri, serif"><span lang="en-US">
	Abstain from disseminating information or content that is </span></font><font face="Calibri, serif"><span lang="en-US"><b>false
	or misleading</b></span></font><font face="Calibri, serif"><span lang="en-US">.</span></font></font></font></p>
</li></ol>
<ol start="10">
	<li><p style="margin-bottom: 0in; line-height: 100%" align="JUSTIFY"><font face="Cambria, serif"><font size="3"><font face="Calibri, serif"><span lang="en-US">
	Be aware that in the event of a lawsuit in certain jurisdictions (e.g. the United States and most common law jurisdictions), 
	all documents and contents you posted on Pernod Ricard Chatter® </span></font><font face="Calibri, serif"><span lang="en-US">
	<b>may have to be disclosed during the proceedings</b></span></font><font face="Calibri, serif"><span lang="en-US">
	 whether these are helpful or damaging to our case.</span></font></font></font></p>
</li></ol>
<p class="western" style="margin-bottom: 0in; line-height: 100%" align="JUSTIFY">
<br>
</p>
<p class="western" style="margin-bottom: 0in; line-height: 100%" align="JUSTIFY">
<font face="Cambria, serif"><font size="3"><font face="Calibri, serif"><font style="font-size: 11pt" size="2">
Please read the ESN Policy carefully and double click on the “I have read and I accept the ESN Policy” 
button to express your consent that you will comply with the commitments set up in the ESN Policy 
while interacting on Pernod Ricard Chatter® and agree to the processing of your personal data in the 
manner set out in the ESN Policy. </font></font></font></font></p>
<p class="western" style="margin-bottom: 0in; line-height: 100%"><br>
</p>
<div type="FOOTER">
	<p style="margin-top: 0.56in; margin-bottom: 0in; line-height: 100%; page-break-before: always" align="CENTER">
	<font face="Cambria, serif"><font size="3"><font color="#808080"><font face="Calibri, serif"><font style="font-size: 8pt" size="1">
	Chatter and the “C” logo are trademarks of salesforce.com, inc. and are used here under license.</font></font></font></font></font></p>
	<p style="margin-bottom: 0in; line-height: 100%"><br>
	</p>
</div>

</body></html>