<html>

<head>
<meta http-equiv=Content-Type content="text/html; charset=utf-8">
<meta name=Generator content="Microsoft Word 12 (filtered)">
<style>
<!--
 /* Font Definitions */
 @font-face
	{font-family:Wingdings;
	panose-1:5 0 0 0 0 0 0 0 0 0;}
@font-face
	{font-family:PMingLiU;
	panose-1:2 2 5 0 0 0 0 0 0 0;}
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Cambria;
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
@font-face
	{font-family:Tahoma;
	panose-1:2 11 6 4 3 5 4 4 2 4;}
@font-face
	{font-family:HelveticaNeue-Bold;
	panose-1:0 0 0 0 0 0 0 0 0 0;}
@font-face
	{font-family:HelveticaNeue-Light;
	panose-1:0 0 0 0 0 0 0 0 0 0;}
@font-face
	{font-family:"\@PMingLiU";
	panose-1:2 2 5 0 0 0 0 0 0 0;}
 /* Style Definitions */
 p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin-top:0cm;
	margin-right:0cm;
	margin-bottom:10.0pt;
	margin-left:0cm;
	line-height:115%;
	font-size:11.0pt;
	font-family:"Calibri","sans-serif";}
p.MsoCommentText, li.MsoCommentText, div.MsoCommentText
	{mso-style-link:"Commentaire Car";
	margin-top:0cm;
	margin-right:0cm;
	margin-bottom:10.0pt;
	margin-left:0cm;
	line-height:115%;
	font-size:10.0pt;
	font-family:"Calibri","sans-serif";}
p.MsoHeader, li.MsoHeader, div.MsoHeader
	{mso-style-link:"En-tête Car";
	margin-top:0cm;
	margin-right:0cm;
	margin-bottom:10.0pt;
	margin-left:0cm;
	line-height:115%;
	font-size:11.0pt;
	font-family:"Calibri","sans-serif";}
p.MsoFooter, li.MsoFooter, div.MsoFooter
	{mso-style-link:"Pied de page Car";
	margin-top:0cm;
	margin-right:0cm;
	margin-bottom:10.0pt;
	margin-left:0cm;
	line-height:115%;
	font-size:11.0pt;
	font-family:"Calibri","sans-serif";}
p.MsoCommentSubject, li.MsoCommentSubject, div.MsoCommentSubject
	{mso-style-link:"Objet du commentaire Car";
	margin-top:0cm;
	margin-right:0cm;
	margin-bottom:10.0pt;
	margin-left:0cm;
	line-height:115%;
	font-size:10.0pt;
	font-family:"Calibri","sans-serif";
	font-weight:bold;}
p.MsoAcetate, li.MsoAcetate, div.MsoAcetate
	{mso-style-link:"Texte de bulles Car";
	margin:0cm;
	margin-bottom:.0001pt;
	font-size:8.0pt;
	font-family:"Tahoma","sans-serif";}
p.MsoListParagraph, li.MsoListParagraph, div.MsoListParagraph
	{margin-top:0cm;
	margin-right:0cm;
	margin-bottom:10.0pt;
	margin-left:36.0pt;
	line-height:115%;
	font-size:11.0pt;
	font-family:"Calibri","sans-serif";}
p.MsoListParagraphCxSpFirst, li.MsoListParagraphCxSpFirst, div.MsoListParagraphCxSpFirst
	{margin-top:0cm;
	margin-right:0cm;
	margin-bottom:0cm;
	margin-left:36.0pt;
	margin-bottom:.0001pt;
	line-height:115%;
	font-size:11.0pt;
	font-family:"Calibri","sans-serif";}
p.MsoListParagraphCxSpMiddle, li.MsoListParagraphCxSpMiddle, div.MsoListParagraphCxSpMiddle
	{margin-top:0cm;
	margin-right:0cm;
	margin-bottom:0cm;
	margin-left:36.0pt;
	margin-bottom:.0001pt;
	line-height:115%;
	font-size:11.0pt;
	font-family:"Calibri","sans-serif";}
p.MsoListParagraphCxSpLast, li.MsoListParagraphCxSpLast, div.MsoListParagraphCxSpLast
	{margin-top:0cm;
	margin-right:0cm;
	margin-bottom:10.0pt;
	margin-left:36.0pt;
	line-height:115%;
	font-size:11.0pt;
	font-family:"Calibri","sans-serif";}
span.En-tteCar
	{mso-style-name:"En-tête Car";
	mso-style-link:En-tête;}
span.PieddepageCar
	{mso-style-name:"Pied de page Car";
	mso-style-link:"Pied de page";}
span.CommentaireCar
	{mso-style-name:"Commentaire Car";
	mso-style-link:Commentaire;}
span.ObjetducommentaireCar
	{mso-style-name:"Objet du commentaire Car";
	mso-style-link:"Objet du commentaire";
	font-weight:bold;}
span.TextedebullesCar
	{mso-style-name:"Texte de bulles Car";
	mso-style-link:"Texte de bulles";
	font-family:"Tahoma","sans-serif";}
span.z-HautduformulaireCar
	{mso-style-name:"z-Haut du formulaire Car";
	mso-style-link:"z-Haut du formulaire";
	font-family:"Arial","sans-serif";
	display:none;}
span.z-BasduformulaireCar
	{mso-style-name:"z-Bas du formulaire Car";
	mso-style-link:"z-Bas du formulaire";
	font-family:"Arial","sans-serif";
	display:none;}
span.gt-ft-text1
	{mso-style-name:gt-ft-text1;}
.MsoChpDefault
	{font-size:10.0pt;}
 /* Page Definitions */
 @page WordSection1
	{size:595.3pt 841.9pt;
	margin:2.0cm 2.0cm 2.0cm 2.0cm;}
div.WordSection1
	{page:WordSection1;}
 /* List Definitions */
 ol
	{margin-bottom:0cm;}
ul
	{margin-bottom:0cm;}
-->
</style>

</head>

<body lang=FR>

<div class=WordSection1>

<p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
text-align:center;line-height:normal;text-autospace:none'><b><i><u><span
style='font-size:14.0pt'><span style='text-decoration:none'>&nbsp;</span></span></u></i></b></p>

<p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
text-align:center;line-height:normal;text-autospace:none'><b><u><span
lang=EN-US style='font-size:14.0pt'>Pernod Ricard Chatter®</span></u></b></p>

<p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
text-align:center;line-height:normal;text-autospace:none'><b><u><span
lang=EN-US style='font-size:14.0pt'>External User Agreement</span></u></b></p>

<p class=MsoNormal align=center style='margin-bottom:0cm;margin-bottom:.0001pt;
text-align:center;line-height:normal;text-autospace:none'><span lang=EN-US
style='font-size:11.5pt;color:black'>&nbsp;</span></p>

<p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;text-align:
justify;line-height:normal;text-autospace:none'><span lang=EN-US
style='font-size:11.5pt;color:black'>&nbsp;</span></p>

<p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;text-align:
justify;line-height:normal;text-autospace:none'><span lang=EN-US
style='font-size:11.5pt'>I </span><span lang=EN-US style='font-size:11.5pt;
color:#333333'>acknowledge that I have received an invitation (hereinafter ‘<b>Invitation</b>’)
from </span><span lang=EN-US style='font-size:11.5pt;color:black'>the Pernod
Ricard entity with which I have, or the company employing me has, a business
relationship </span><span lang=EN-US style='font-size:11.5pt;color:#333333'>(hereinafter
‘<b>Pernod Ricard</b>’)</span><span lang=EN-US style='font-size:11.5pt;
color:black'>, to join the Pernod Ricard </span><span lang=EN-US
style='font-size:11.5pt;color:#333333'>(meaning the Pernod Ricard S.A. company
and its affiliates), enterprise social network called ‘Pernod Ricard Chatter®’
(hereinafter, the ‘<b>ESN’</b>)</span><span lang=EN-US style='font-size:11.5pt;
color:black'>, as an external user.</span></p>

<p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;text-align:
justify;line-height:normal;text-autospace:none'><span lang=EN-US
style='font-size:11.5pt;color:black'>&nbsp;</span></p>

<p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;text-align:
justify;line-height:normal;text-autospace:none'><span lang=EN-US
style='font-size:11.5pt;color:black'>As a result of such invitation I
acknowledge that I will</span><span lang=EN-US style='font-size:11.5pt'> </span><span
lang=EN-US style='font-size:11.5pt;color:#333333'>have access to information
relating to Pernod Ricard, its activity, affiliates, products, business
partners, customers, competitors and employees including personal data
(hereinafter, the ‘<b>Data</b>’) as an external user of Pernod Ricard Chatter®.
</span><span lang=EN-US style='font-size:11.5pt'>I agree that my access to the ESN
is subject to my commitment to ensure </span><span lang=EN-US style='font-size:
11.5pt;color:#333333'> the confidentiality of the Data and that no access will
be provided if I do not read and accept (i) the ESN Policy and (ii) this external
user agreement (hereinafter the ‘<b>External User Agreement</b>’).</span></p>

<p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;text-align:
justify;line-height:normal;text-autospace:none'><span lang=EN-US
style='font-size:11.5pt;color:black'>&nbsp;</span></p>

<p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;text-align:
justify;line-height:normal;text-autospace:none'><span lang=EN-US
style='font-size:11.5pt;color:black'>Therefore, by clicking the acceptance
button, located below the ESN Policy which governs the usage of the ESN by both
external and internal users, I accept to be bound by the <b>ESN Policy</b>. </span></p>

<p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;text-align:
justify;line-height:normal;text-autospace:none'><span lang=EN-US
style='font-size:11.5pt;color:black'>&nbsp;</span></p>

<p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;text-align:
justify;line-height:normal;text-autospace:none'><span lang=EN-US
style='font-size:11.5pt;color:black'>In addition to the commitments stated in
the ESN Policy, I accept, as an external user, by clicking on the ‘I have read
and I accept the External User Agreement’ button located below the External
User Agreement to take all appropriate measures to ensure the confidentiality
of the Data and to use the ESN properly. In particular (but without limitation)
I agree:</span></p>

<p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;text-align:
justify;line-height:normal;vertical-align:top'><span lang=EN-US
style='font-size:11.5pt;color:black'>&nbsp;</span></p>

<p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;text-align:
justify;line-height:normal;vertical-align:top'><span lang=EN-US
style='font-size:11.5pt;color:#333333'>&nbsp;</span></p>

<p class=MsoListParagraphCxSpFirst style='margin-top:0cm;margin-right:0cm;
margin-bottom:0cm;margin-left:53.4pt;margin-bottom:.0001pt;text-align:justify;
text-indent:-18.0pt;line-height:normal;vertical-align:top'><span lang=EN-US
style='font-size:11.5pt;font-family:"Cambria","serif";color:#333333'>-<span
style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span><span lang=EN-US style='font-size:11.5pt;color:#333333'>to use
the ESN only to the extent needed to perform my duties and responsibilities in
the framework of the business relationship with Pernod Ricard; </span></p>

<p class=MsoListParagraphCxSpMiddle style='margin-top:0cm;margin-right:0cm;
margin-bottom:0cm;margin-left:53.4pt;margin-bottom:.0001pt;text-align:justify;
text-indent:-18.0pt;line-height:normal;vertical-align:top'><span lang=EN-US
style='font-size:11.5pt;font-family:"Cambria","serif";color:#333333'>-<span
style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span><span lang=EN-US style='font-size:11.5pt;color:#333333'>not to
use the Data for purposes other than the performance of my duties and
responsibilities in the framework of the business relationship with Pernod
Ricard, and for purposes other than those provided in the Invitation and the
ESN Policy;</span></p>

<p class=MsoListParagraphCxSpMiddle style='margin-top:0cm;margin-right:0cm;
margin-bottom:0cm;margin-left:53.4pt;margin-bottom:.0001pt;text-align:justify;
text-indent:-18.0pt;line-height:normal;vertical-align:top'><span lang=EN-US
style='font-size:11.5pt;font-family:"Cambria","serif";color:#333333'>-<span
style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span><span lang=EN-US style='font-size:11.5pt;color:#333333'>to comply
with the security instructions and other instructions of use of the ESN which
will be provided from time to time; </span></p>

<p class=MsoListParagraphCxSpMiddle style='margin-top:0cm;margin-right:0cm;
margin-bottom:0cm;margin-left:53.4pt;margin-bottom:.0001pt;text-align:justify;
text-indent:-18.0pt;line-height:normal;vertical-align:top'><span lang=EN-US
style='font-size:11.5pt;font-family:"Cambria","serif";color:#333333'>-<span
style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span><span lang=EN-US style='font-size:11.5pt;color:#333333'>to adapt
the configuration of my end user terminal as indicated by Pernod Ricard in
order to be able to use the ESN properly and securely; </span></p>

<p class=MsoListParagraphCxSpMiddle style='margin-top:0cm;margin-right:0cm;
margin-bottom:0cm;margin-left:53.4pt;margin-bottom:.0001pt;text-align:justify;
text-indent:-18.0pt;line-height:normal;vertical-align:top'><span lang=EN-US
style='font-size:11.5pt;font-family:"Cambria","serif";color:#333333'>-<span
style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span><span lang=EN-US style='font-size:11.5pt;color:#333333'>to  take
all precautions to prevent a misuse or a fraudulent use of the Data;</span></p>

<p class=MsoListParagraphCxSpMiddle style='margin-top:0cm;margin-right:0cm;
margin-bottom:0cm;margin-left:53.4pt;margin-bottom:.0001pt;text-align:justify;
text-indent:-18.0pt;line-height:normal;vertical-align:top'><span lang=EN-US
style='font-size:11.5pt;font-family:"Cambria","serif";color:#333333'>-<span
style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span><span lang=EN-US style='font-size:11.5pt;color:#333333'>not to
copy nor reproduce the Data in any manner and on any material whatsoever, including
partially, without the prior written consent of Pernod Ricard;</span></p>

<p class=MsoListParagraphCxSpMiddle style='margin-top:0cm;margin-right:0cm;
margin-bottom:0cm;margin-left:53.4pt;margin-bottom:.0001pt;text-align:justify;
text-indent:-18.0pt;line-height:normal;vertical-align:top'><span lang=EN-US
style='font-size:11.5pt;font-family:"Cambria","serif";color:#333333'>-<span
style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span><span lang=EN-US style='font-size:11.5pt;color:#333333'>not to
disclose to third parties in any manner and in any form whatsoever, including
partially, the Data without the prior written consent of Pernod Ricard;</span></p>

<p class=MsoListParagraphCxSpLast style='margin-top:0cm;margin-right:0cm;
margin-bottom:0cm;margin-left:53.4pt;margin-bottom:.0001pt;text-align:justify;
text-indent:-18.0pt;line-height:normal;vertical-align:top'><span lang=EN-US
style='font-size:11.5pt;font-family:"Cambria","serif";color:#333333'>-<span
style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span><span lang=EN-US style='font-size:11.5pt;color:#333333'>not to
disclose my username or password to the ESN, or otherwise allow access to the
ESN, to a third party.</span></p>

<p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;text-align:
justify;line-height:normal;vertical-align:top'><span lang=EN-US
style='font-size:11.5pt;color:#333333'>&nbsp;</span></p>

<p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;text-align:
justify;line-height:normal;vertical-align:top'><span lang=EN-US
style='font-size:11.5pt;color:#333333'>The disclosure of the Data is allowed on
exceptional occasions, provided that the following conditions are met: the recipient
of the Data (i) needs absolutely to know such Data </span><span lang=EN-US
style='font-size:11.5pt'>to perform his duties and responsibilities in the
framework of a business relationship with Pernod Ricard</span><span lang=EN-US
style='font-size:11.5pt;color:#333333'>, and (ii) has previously signed a
confidentiality agreement with Pernod Ricard, covering the concerned
information, that is no less restrictive than this document.</span></p>

<p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;text-align:
justify;line-height:normal;vertical-align:top'><span lang=EN-US
style='font-size:11.5pt;color:#333333'>&nbsp;</span></p>

<p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;text-align:
justify;line-height:normal;vertical-align:top'><span lang=EN-US
style='font-size:11.5pt;color:#333333'>I acknowledge that all information,
documents and materials which I post on the ESN can be freely used and
disclosed by Pernod Ricard unless they have been clearly marked as proprietary
and/or confidential.</span></p>

<p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;text-align:
justify;line-height:normal;vertical-align:top'><span lang=EN-US
style='font-size:11.5pt;color:#333333'> </span></p>

<p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;text-align:
justify;line-height:normal;vertical-align:top'><span lang=EN-US
style='font-size:11.5pt;color:#333333'>Access to the ESN does not grant the user
any intellectual property right nor any property right of any kind to any Data
nor material available on the ESN.</span></p>

<p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;text-align:
justify;line-height:normal;vertical-align:top'><span lang=EN-US
style='font-size:11.5pt;color:#333333'>&nbsp;</span></p>

<p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;text-align:
justify;line-height:normal;vertical-align:top'><span lang=EN-US
style='font-size:11.5pt;color:#333333'>I understand that access to the ESN starts
once I have accepted this Agreement and the ESN Policy and may be immediately terminated
by Pernod Ricard for cause (e.g. violation of the ESN Policy or this External
User Agreement) or at its discretion. In any event, I acknowledge that access
will be stopped if the business relationship with Pernod Ricard or my
employment agreement with the company having such business relationship comes
to an end.</span></p>

<p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;text-align:
justify;line-height:normal;vertical-align:top'><span lang=EN-US
style='font-size:11.5pt;color:#333333'> </span></p>

<p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;text-align:
justify;line-height:normal;vertical-align:top'><span lang=EN-US
style='font-size:11.5pt;color:#333333'>At the end of the business relationship with
Pernod Ricard, or at the end of my employment contract with the company which
is in a business relationship with Pernod Ricard, whichever comes first, or at
any time upon Pernod Ricard's request, I agree to return within three (3) days
the Data and any material on which the Data were reproduced, or to destroy said
material, as well as any copy whatsoever and provide a certificate to certify
such destruction duly signed by the person having the authority to sign it.</span></p>

<p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;text-align:
justify;line-height:normal;vertical-align:top'><span lang=EN-US
style='font-size:11.5pt;color:#333333'><br>
I understand that the commitments stated in this document do not prove any subordinate
relationship with respect to Pernod Ricard. </span></p>

<p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;text-align:
justify;line-height:normal;vertical-align:top'><span lang=EN-US
style='font-size:11.5pt;color:#333333'><br>
This confidentiality obligation shall remain in force throughout the term of this
External User Agreement and for a period of ten (10) years after the expiration
or the termination date of this External User Agreement for any reason
whatsoever, provided that this requirement relates to the use and the
communication of Data.</span></p>

<p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;text-align:
justify;text-indent:35.4pt;line-height:normal;vertical-align:top'><span
lang=EN-US style='font-size:11.5pt;color:#333333'>&nbsp;</span></p>

<p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;text-align:
justify;line-height:normal;vertical-align:top'><span lang=EN-US
style='font-size:11.5pt;color:#333333'>Any violation of this External User Agreement
will entitle Pernod Ricard to seek any remedy provided by law against me or my
employer.</span></p>

<p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;text-align:
justify;line-height:normal;vertical-align:top'><span lang=EN-US
style='font-size:11.5pt;color:#333333'>&nbsp;</span></p>

<p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;text-align:
justify;line-height:normal;text-autospace:none'><span lang=EN-US
style='font-size:11.5pt;color:black'>I acknowledge that this External User Agreement
is governed by the law of the country in which the Pernod Ricard entity that
invited me to access the ESN is located.</span></p>

<p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;text-align:
justify;line-height:normal;text-autospace:none'><span lang=EN-US
style='font-size:11.5pt;color:black'>&nbsp;</span></p>

<p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;text-align:
justify;line-height:normal;text-autospace:none'><span lang=EN-US
style='font-size:11.5pt;color:black'>The External User Agreement and the ESN
Policy may be amended from time to time and I agree with the External User
Agreement and the ESN Policy as modified as long as I have access to the ESN.
If I do not agree to any revised External User Agreement and/or a revised ESN
Policy I will notify Pernod Ricard promptly and my access will be terminated.  <a
name="_GoBack"></a></span></p>

<p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;text-align:
justify;line-height:normal;text-autospace:none'><span lang=EN-US
style='font-size:11.5pt;color:black'>&nbsp;</span></p>

<p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;text-align:
justify;line-height:normal;text-autospace:none'><span lang=EN-US
style='font-size:11.5pt;color:black'>&nbsp;</span></p>

<p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;text-align:
justify;line-height:normal;text-autospace:none'><span lang=EN-US
style='font-size:11.5pt;color:black'>&nbsp;</span></p>

<p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;text-align:
justify;line-height:normal;text-autospace:none'><b><span lang=EN-US
style='font-size:11.5pt;color:black'>&nbsp;</span></b></p>

</div>

</body>

</html>
