<?xml version="1.0" encoding="UTF-8"?>
<Workflow xmlns="http://soap.sforce.com/2006/04/metadata">
    <alerts>
        <fullName>ASI_MFM_CAP_HK_Payment_Approved_Notification_Email_Alert</fullName>
        <ccEmails>thomas.chan@pernod-ricard.com</ccEmails>
        <ccEmails>vincent.kwok@pernod-ricard.com</ccEmails>
        <description>CAP HK Payment Approved Notification Email Alert</description>
        <protected>false</protected>
        <recipients>
            <recipient>ASI_MFM_CAP_HK_Finance_Email_Recipient</recipient>
            <type>group</type>
        </recipients>
        <recipients>
            <type>owner</type>
        </recipients>
        <senderAddress>pra.sfdcitsupport@pernod-ricard.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>ASI_MFM_CAP_Email_Folder/ASI_MFM_CAP_HK_Payment_Approved_Notification_Email_Template</template>
    </alerts>
    <alerts>
        <fullName>ASI_MFM_CAP_HK_Payment_Approved_Notification_Email_Alert_Buffer</fullName>
        <ccEmails>thomas.chan@pernod-ricard.com</ccEmails>
        <ccEmails>vincent.kwok@pernod-ricard.com</ccEmails>
        <description>CAP HK Payment Approved Notification Email Alert Buffer</description>
        <protected>false</protected>
        <recipients>
            <recipient>ASI_MFM_CAP_HK_Finance_Email_Recipient</recipient>
            <type>group</type>
        </recipients>
        <recipients>
            <recipient>ASI_MFM_CAP_HK_Logistics_Buffer_Users</recipient>
            <type>group</type>
        </recipients>
        <recipients>
            <type>owner</type>
        </recipients>
        <senderAddress>pra.sfdcitsupport@pernod-ricard.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>ASI_MFM_CAP_Email_Folder/ASI_MFM_CAP_HK_Payment_Approved_Notification_Email_Template</template>
    </alerts>
    <alerts>
        <fullName>ASI_MFM_CAP_HK_Payment_Approved_Notification_Email_Alert_Indent</fullName>
        <ccEmails>thomas.chan@pernod-ricard.com</ccEmails>
        <ccEmails>vincent.kwok@pernod-ricard.com</ccEmails>
        <description>CAP HK Payment Approved Notification Email Alert Indent</description>
        <protected>false</protected>
        <recipients>
            <recipient>ASI_MFM_CAP_HK_Finance_Email_Recipient</recipient>
            <type>group</type>
        </recipients>
        <recipients>
            <recipient>ASI_MFM_CAP_HK_Logistics_Indent_Users</recipient>
            <type>group</type>
        </recipients>
        <recipients>
            <type>owner</type>
        </recipients>
        <senderAddress>pra.sfdcitsupport@pernod-ricard.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>ASI_MFM_CAP_Email_Folder/ASI_MFM_CAP_HK_Payment_Approved_Notification_Email_Template</template>
    </alerts>
    <alerts>
        <fullName>ASI_MFM_CAP_HK_Payment_Buffer_Auto_Submitted_Email_Alert</fullName>
        <ccEmails>thomas.chan@pernod-ricard.com</ccEmails>
        <ccEmails>vincent.kwok@pernod-ricard.com</ccEmails>
        <description>CAP HK Payment Buffer Auto Submitted Email Alert</description>
        <protected>false</protected>
        <recipients>
            <recipient>ASI_MFM_CAP_HK_Logistics_Buffer_Users</recipient>
            <type>group</type>
        </recipients>
        <senderAddress>pra.sfdcitsupport@pernod-ricard.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>ASI_MFM_CAP_Email_Folder/ASI_MFM_CAP_HK_Buffer_Auto_Submitted</template>
    </alerts>
    <alerts>
        <fullName>ASI_MFM_CAP_HK_Payment_Buffer_Over_Goods_In_Transit_Amount_Limit_Email_Alert</fullName>
        <ccEmails>thomas.chan@pernod-ricard.com</ccEmails>
        <ccEmails>vincent.kwok@pernod-ricard.com</ccEmails>
        <description>CAP HK Payment Buffer Over Goods In Transit Amount Limit Email Alert</description>
        <protected>false</protected>
        <recipients>
            <recipient>ASI_MFM_CAP_HK_Logistics_Buffer_Users</recipient>
            <type>group</type>
        </recipients>
        <senderAddress>pra.sfdcitsupport@pernod-ricard.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>ASI_MFM_CAP_Email_Folder/ASI_MFM_CAP_HK_Payment_Over_Tolerance_Limit_Email_Template</template>
    </alerts>
    <alerts>
        <fullName>ASI_MFM_CAP_HK_Payment_Indent_Auto_Submitted_Email_Alert</fullName>
        <ccEmails>thomas.chan@pernod-ricard.com</ccEmails>
        <ccEmails>vincent.kwok@pernod-ricard.com</ccEmails>
        <description>CAP HK Payment Indent Auto Submitted Email Alert</description>
        <protected>false</protected>
        <recipients>
            <recipient>ASI_MFM_CAP_HK_Logistics_Indent_Users</recipient>
            <type>group</type>
        </recipients>
        <senderAddress>pra.sfdcitsupport@pernod-ricard.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>ASI_MFM_CAP_Email_Folder/ASI_MFM_CAP_HK_Indent_Auto_Submitted</template>
    </alerts>
    <alerts>
        <fullName>ASI_MFM_CAP_HK_Payment_Indent_Over_Goods_In_Transit_Amount_Limit_Email_Alert</fullName>
        <ccEmails>thomas.chan@pernod-ricard.com</ccEmails>
        <ccEmails>vincent.kwok@pernod-ricard.com</ccEmails>
        <description>CAP HK Payment Indent Over Goods In Transit Amount Limit Email Alert</description>
        <protected>false</protected>
        <recipients>
            <recipient>ASI_MFM_CAP_HK_Logistics_Indent_Users</recipient>
            <type>group</type>
        </recipients>
        <senderAddress>pra.sfdcitsupport@pernod-ricard.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>ASI_MFM_CAP_Email_Folder/ASI_MFM_CAP_HK_Payment_Over_Tolerance_Limit_Email_Template</template>
    </alerts>
    <alerts>
        <fullName>ASI_MFM_CAP_HK_Payment_Missing_Info_for_Auto_Submit_Email_Alert</fullName>
        <ccEmails>thomas.chan@pernod-ricard.com</ccEmails>
        <ccEmails>vincent.kwok@pernod-ricard.com</ccEmails>
        <description>CAP HK Payment Missing Info for Auto Submit Email Alert</description>
        <protected>false</protected>
        <recipients>
            <type>owner</type>
        </recipients>
        <senderAddress>pra.sfdcitsupport@pernod-ricard.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>ASI_MFM_CAP_Email_Folder/ASI_MFM_CAP_HK_Payment_Missing_Info_Email_Template</template>
    </alerts>
    <alerts>
        <fullName>ASI_MFM_CAP_HK_Payment_Rejected_Notification_Email_Alert</fullName>
        <ccEmails>thomas.chan@pernod-ricard.com</ccEmails>
        <ccEmails>vincent.kwok@pernod-ricard.com</ccEmails>
        <description>CAP HK Payment Rejected Notification Email Alert</description>
        <protected>false</protected>
        <recipients>
            <type>owner</type>
        </recipients>
        <senderAddress>pra.sfdcitsupport@pernod-ricard.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>ASI_MFM_CAP_Email_Folder/ASI_MFM_CAP_HK_Payment_Rejected_Notification_Email_Template</template>
    </alerts>
    <alerts>
        <fullName>ASI_MFM_CAP_HK_Payment_Rejected_Notification_Email_Alert_Buffer</fullName>
        <ccEmails>thomas.chan@pernod-ricard.com</ccEmails>
        <ccEmails>vincent.kwok@pernod-ricard.com</ccEmails>
        <description>CAP HK Payment Rejected Notification Email Alert Buffer</description>
        <protected>false</protected>
        <recipients>
            <recipient>ASI_MFM_CAP_HK_Logistics_Buffer_Users</recipient>
            <type>group</type>
        </recipients>
        <recipients>
            <type>owner</type>
        </recipients>
        <senderAddress>pra.sfdcitsupport@pernod-ricard.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>ASI_MFM_CAP_Email_Folder/ASI_MFM_CAP_HK_Payment_Rejected_Notification_Email_Template</template>
    </alerts>
    <alerts>
        <fullName>ASI_MFM_CAP_HK_Payment_Rejected_Notification_Email_Alert_Indent</fullName>
        <ccEmails>thomas.chan@pernod-ricard.com</ccEmails>
        <ccEmails>vincent.kwok@pernod-ricard.com</ccEmails>
        <description>CAP HK Payment Rejected Notification Email Alert Indent</description>
        <protected>false</protected>
        <recipients>
            <recipient>ASI_MFM_CAP_HK_Logistics_Indent_Users</recipient>
            <type>group</type>
        </recipients>
        <recipients>
            <type>owner</type>
        </recipients>
        <senderAddress>pra.sfdcitsupport@pernod-ricard.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>ASI_MFM_CAP_Email_Folder/ASI_MFM_CAP_HK_Payment_Rejected_Notification_Email_Template</template>
    </alerts>
    <alerts>
        <fullName>ASI_MFM_CAP_Payment_Approved_Notification_Email_Alert</fullName>
        <description>CAP Payment Approved Notification Email Alert</description>
        <protected>false</protected>
        <recipients>
            <field>ASI_MFM_Sys_Submitter_Email_Address__c</field>
            <type>email</type>
        </recipients>
        <recipients>
            <type>owner</type>
        </recipients>
        <recipients>
            <recipient>cynthia.sin@pernod-ricard.com</recipient>
            <type>user</type>
        </recipients>
        <recipients>
            <recipient>elsa.ma@pernod-ricard.com</recipient>
            <type>user</type>
        </recipients>
        <recipients>
            <recipient>jenevieve.mok@pernod-ricard.com</recipient>
            <type>user</type>
        </recipients>
        <recipients>
            <recipient>venus.chan@pernod-ricard.com</recipient>
            <type>user</type>
        </recipients>
        <senderAddress>pra.sfdcitsupport@pernod-ricard.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>ASI_MFM_CAP_Email_Folder/ASI_MFM_CAP_Payment_Approved_Notification_Email_Template</template>
    </alerts>
    <alerts>
        <fullName>ASI_MFM_CAP_Payment_Rejected_Notification_Email_Alert</fullName>
        <description>CAP Payment Rejected Notification Email Alert</description>
        <protected>false</protected>
        <recipients>
            <field>ASI_MFM_Sys_Submitter_Email_Address__c</field>
            <type>email</type>
        </recipients>
        <recipients>
            <type>owner</type>
        </recipients>
        <senderAddress>pra.sfdcitsupport@pernod-ricard.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>ASI_MFM_CAP_Email_Folder/ASI_MFM_CAP_Payment_Rejected_Notification_Email_Template</template>
    </alerts>
    <alerts>
        <fullName>ASI_MFM_CAP_SG_Payment_Approval_Request_Email_Alert</fullName>
        <description>CAP SG Payment Approval Request Email Alert</description>
        <protected>false</protected>
        <recipients>
            <recipient>ASI_MFM_CAP_SG_Finance</recipient>
            <type>group</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>ASI_MFM_CAP_Email_Folder/ASI_MFM_CAP_SG_Payment_Approval_Request</template>
    </alerts>
    <alerts>
        <fullName>ASI_MFM_CAP_TH_Payment_Approval_Request_Email_Alert</fullName>
        <description>CAP TH Payment Approval Request Email Alert</description>
        <protected>false</protected>
        <recipients>
            <recipient>ASI_MFM_CAP_TH_Finance</recipient>
            <type>group</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>ASI_MFM_CAP_Email_Folder/ASI_MFM_CAP_TH_Payment_Approval_Request</template>
    </alerts>
    <alerts>
        <fullName>ASI_MFM_CN_CashOutAlert</fullName>
        <description>CN CashOutAlert</description>
        <protected>false</protected>
        <recipients>
            <field>ASI_MFM_Supplier_Email__c</field>
            <type>email</type>
        </recipients>
        <recipients>
            <recipient>patrick.yan@pernod-ricard.com</recipient>
            <type>user</type>
        </recipients>
        <recipients>
            <recipient>shirley.li@pernod-ricard.com</recipient>
            <type>user</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>ASI_MFM_CN_Email_Templates/ASI_MFM_CN_PaymentCashOutEmail</template>
    </alerts>
    <alerts>
        <fullName>ASI_MFM_CN_Payment_Approved_Notification_to_Owner_CN</fullName>
        <description>Payment Approved Notification to Owner (CN)</description>
        <protected>false</protected>
        <recipients>
            <type>owner</type>
        </recipients>
        <recipients>
            <field>ASI_MFM_Budget_Owner__c</field>
            <type>userLookup</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>ASI_MFM_CN_Email_Templates/ASI_MFM_CN_Payment_Approved_Template</template>
    </alerts>
    <alerts>
        <fullName>ASI_MFM_CN_Payment_Rejected_Notification_to_Owner_CN</fullName>
        <description>Payment Rejected Notification to Owner (CN)</description>
        <protected>false</protected>
        <recipients>
            <type>owner</type>
        </recipients>
        <recipients>
            <field>ASI_MFM_Budget_Owner__c</field>
            <type>userLookup</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>ASI_MFM_CN_Email_Templates/ASI_MFM_CN_Payment_Rejected_Template</template>
    </alerts>
    <alerts>
        <fullName>ASI_MFM_CN_Payment_Submitted_to_Finance_Notification</fullName>
        <description>Payment Submitted to Finance Notification</description>
        <protected>false</protected>
        <recipients>
            <type>owner</type>
        </recipients>
        <recipients>
            <field>ASI_MFM_Budget_Owner__c</field>
            <type>userLookup</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>ASI_MFM_CN_Email_Templates/ASI_MFM_CN_Payment_Notify_Goto_Fin</template>
    </alerts>
    <alerts>
        <fullName>ASI_MFM_CN_Send_notification_to_budget_owner_of_Payment</fullName>
        <description>Send notification to budget owner of Payment</description>
        <protected>false</protected>
        <recipients>
            <field>ASI_MFM_Budget_Owner__c</field>
            <type>userLookup</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>ASI_MFM_CN_Email_Templates/ASI_MFM_CN_Payment_Notify_Budget_Owner</template>
    </alerts>
    <alerts>
        <fullName>ASI_MFM_CN_StructureCost_Approved_Alert</fullName>
        <description>ASI_MFM_CN_StructureCost_Approved_Alert</description>
        <protected>false</protected>
        <recipients>
            <type>owner</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>ASI_MFM_CN_Email_Templates/ASI_MFM_CN_StructureCost_Approved</template>
    </alerts>
    <alerts>
        <fullName>ASI_MFM_CN_StructureCost_Rejected_Alert</fullName>
        <description>ASI_MFM_CN_StructureCost_Rejected_Alert</description>
        <protected>false</protected>
        <recipients>
            <type>owner</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>ASI_MFM_CN_Email_Templates/ASI_MFM_CN_StructureCost_Rejected</template>
    </alerts>
    <alerts>
        <fullName>ASI_MFM_GF_Direct_Payment_Fin_Alert</fullName>
        <description>ASI_MFM_GF_Direct_Payment_Fin_Alert</description>
        <protected>false</protected>
        <recipients>
            <recipient>amit.khandelwal@pernod-ricard.com</recipient>
            <type>user</type>
        </recipients>
        <recipients>
            <recipient>frexyruby.torres@pernod-ricard.com</recipient>
            <type>user</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>ASI_GF_MFM_Email_Folder/ASI_MFM_GF_DirectPayment_Email_Fin_VF</template>
    </alerts>
    <alerts>
        <fullName>ASI_MFM_GF_PaymentInterfaceWarningAlert</fullName>
        <description>ASI_MFM_GF_PaymentInterfaceWarningAlert</description>
        <protected>false</protected>
        <recipients>
            <recipient>amit.khandelwal@pernod-ricard.com</recipient>
            <type>user</type>
        </recipients>
        <recipients>
            <recipient>frexyruby.torres@pernod-ricard.com</recipient>
            <type>user</type>
        </recipients>
        <senderAddress>pra.sfdcitsupport@pernod-ricard.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>ASI_GF_MFM_Email_Folder/ASI_MFM_GF_PaymentInterfaceWarningEmail</template>
    </alerts>
    <alerts>
        <fullName>ASI_MFM_GF_Payment_Approved_Alert_Fin</fullName>
        <description>ASI MFM GF Payment Approved Alert - Fin</description>
        <protected>false</protected>
        <recipients>
            <recipient>amy.foster@pernod-ricard.com</recipient>
            <type>user</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>ASI_GF_MFM_Email_Folder/ASI_MFM_GF_Payment_Approved_Email_Fin_VF</template>
    </alerts>
    <alerts>
        <fullName>ASI_MFM_GF_Payment_Approved_Email_Alert</fullName>
        <description>ASI MFM GF Payment Approved Email Alert</description>
        <protected>false</protected>
        <recipients>
            <type>owner</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>ASI_GF_MFM_Email_Folder/ASI_MFM_GF_Payment_Approved_Email_Template</template>
    </alerts>
    <alerts>
        <fullName>ASI_MFM_GF_Payment_Rejected_Email_Alert</fullName>
        <description>ASI MFM GF Payment Rejected Email Alert</description>
        <protected>false</protected>
        <recipients>
            <type>owner</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>ASI_GF_MFM_Email_Folder/ASI_MFM_GF_Payment_Rejection_Notification_Email_Template</template>
    </alerts>
    <alerts>
        <fullName>ASI_MFM_GF_Payment_SriLankaAppEmailFin</fullName>
        <description>ASI_MFM_GF_Payment_SriLankaAppEmailFin</description>
        <protected>false</protected>
        <recipients>
            <recipient>amy.foster@pernod-ricard.com</recipient>
            <type>user</type>
        </recipients>
        <recipients>
            <recipient>harshatha.shetty@pernod-ricard.com</recipient>
            <type>user</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>ASI_GF_MFM_Email_Folder/ASI_MFM_GF_Payment_AppEmailFinSriLanka</template>
    </alerts>
    <alerts>
        <fullName>ASI_MFM_KR_CashOutFVNotice</fullName>
        <description>ASI_MFM_KR_CashOutFVNotice</description>
        <protected>false</protected>
        <recipients>
            <recipient>ASI_MFM_KR_Trade_MKT_Prepayment</recipient>
            <type>group</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>ASI_MFM_KR_Email_Folder/ASI_MFM_KR_CashOutFVNotice</template>
    </alerts>
    <alerts>
        <fullName>ASI_MFM_KR_Payment_Approved_Alert</fullName>
        <description>ASI MFM KR Payment Approved Alert</description>
        <protected>false</protected>
        <recipients>
            <type>owner</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>ASI_MFM_KR_Email_Folder/ASI_MFM_KR_Payment_Approved</template>
    </alerts>
    <alerts>
        <fullName>ASI_MFM_KR_Payment_Rejected_Email_Alert</fullName>
        <description>ASI MFM KR Payment Rejected Email Alert</description>
        <protected>false</protected>
        <recipients>
            <type>owner</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>ASI_MFM_KR_Email_Folder/ASI_MFM_KR_Payment_Rejected</template>
    </alerts>
    <alerts>
        <fullName>ASI_MFM_MY_Payment_Approved_Alert</fullName>
        <description>ASI MFM MY Payment Approved Alert</description>
        <protected>false</protected>
        <recipients>
            <type>owner</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>ASI_MY_MFM_Email_Folder/ASI_MFM_MY_Payment_Approved_Notification</template>
    </alerts>
    <alerts>
        <fullName>ASI_MFM_MY_Payment_Rejected_Email_Alert</fullName>
        <description>ASI MFM MY Payment Rejected Email Alert</description>
        <protected>false</protected>
        <recipients>
            <type>owner</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>ASI_MY_MFM_Email_Folder/ASI_MFM_MY_Payment_Rejected_Email</template>
    </alerts>
    <alerts>
        <fullName>ASI_MFM_PH_Payment_Approved_Alert</fullName>
        <description>ASI MFM PH Payment Approved Alert</description>
        <protected>false</protected>
        <recipients>
            <type>owner</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>ASI_MFM_PH_Email_Folder/ASI_MFM_PH_Payment_Approved</template>
    </alerts>
    <alerts>
        <fullName>ASI_MFM_PH_Payment_Rejected_Email_Alert</fullName>
        <description>ASI MFM PH Payment Rejected Email Alert</description>
        <protected>false</protected>
        <recipients>
            <type>owner</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>ASI_MFM_PH_Email_Folder/ASI_MFM_PH_Payment_Rejected</template>
    </alerts>
    <alerts>
        <fullName>ASI_MFM_Payment_Approval_Notification_Email_Alert</fullName>
        <description>Payment Approval Notification Email Alert</description>
        <protected>false</protected>
        <recipients>
            <field>ASI_MFM_Sys_Submitter_Email_Address__c</field>
            <type>email</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>ASI_MFM_TW_MFM_Email_Folder/ASI_MFM_Payment_Approval_Notification_Email_Template</template>
    </alerts>
    <alerts>
        <fullName>ASI_MFM_Payment_Rejection_Notification_Email_Alert</fullName>
        <description>Payment Rejection Notification Email Alert</description>
        <protected>false</protected>
        <recipients>
            <field>ASI_MFM_Sys_Approver_Email_Address__c</field>
            <type>email</type>
        </recipients>
        <recipients>
            <field>ASI_MFM_Sys_Submitter_Email_Address__c</field>
            <type>email</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>ASI_MFM_TW_MFM_Email_Folder/ASI_MFM_Payment_Rejection_Notification_Email_Template</template>
    </alerts>
    <alerts>
        <fullName>ASI_MFM_SC_Payment_Approved_Notification_Email_Alert</fullName>
        <description>SC Payment Approved Notification Email Alert</description>
        <protected>false</protected>
        <recipients>
            <field>ASI_MFM_Sys_Submitter_Email_Address__c</field>
            <type>email</type>
        </recipients>
        <recipients>
            <type>owner</type>
        </recipients>
        <senderAddress>itservicedesk@pernod-ricard.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>ASI_MFM_CAP_Email_Folder/ASI_MFM_SC_Payment_Approved_Email</template>
    </alerts>
    <alerts>
        <fullName>ASI_MFM_SC_Payment_Rejected_Notification_Email_Alert</fullName>
        <description>SC Payment Rejected Notification Email Alert</description>
        <protected>false</protected>
        <recipients>
            <field>ASI_MFM_Sys_Submitter_Email_Address__c</field>
            <type>email</type>
        </recipients>
        <recipients>
            <type>owner</type>
        </recipients>
        <senderAddress>itservicedesk@pernod-ricard.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>ASI_MFM_CAP_Email_Folder/ASI_MFM_SC_Payment_Rejected_Email</template>
    </alerts>
    <alerts>
        <fullName>ASI_MFM_SG_Payment_Approved_Alert</fullName>
        <description>ASI MFM SG Payment Approved Alert</description>
        <protected>false</protected>
        <recipients>
            <type>owner</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>ASI_MFM_SG_Email_Template/ASI_MFM_SG_Payment_Approved</template>
    </alerts>
    <alerts>
        <fullName>ASI_MFM_SG_Payment_Rejected_Email_Alert</fullName>
        <description>ASI MFM SG Payment Rejected Email Alert</description>
        <protected>false</protected>
        <recipients>
            <type>owner</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>ASI_MFM_SG_Email_Template/ASI_MFM_SG_Payment_Rejected</template>
    </alerts>
    <alerts>
        <fullName>ASI_MFM_TH_Payment_Approved_Alert</fullName>
        <description>ASI MFM TH Payment Approved Alert</description>
        <protected>false</protected>
        <recipients>
            <type>owner</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>ASI_TH_MFM_Email_Template/ASI_TH_MFM_Payment_Approved</template>
    </alerts>
    <alerts>
        <fullName>ASI_MFM_TH_Payment_Rejected_Email_Alert</fullName>
        <description>ASI MFM TH Payment Rejected Email Alert</description>
        <protected>false</protected>
        <recipients>
            <type>owner</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>ASI_TH_MFM_Email_Template/ASI_TH_MFM_Payment_Rejected</template>
    </alerts>
    <alerts>
        <fullName>ASI_MFM_TW_Payment_Complete_Notification</fullName>
        <description>ASI_MFM_TW_Payment_Complete_Notification</description>
        <protected>false</protected>
        <recipients>
            <type>owner</type>
        </recipients>
        <senderAddress>itservicedesk@pernod-ricard.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>ASI_MFM_TW_MFM_Email_Folder/ASI_MFM_TW_Payment_Complete_Notification</template>
    </alerts>
    <fieldUpdates>
        <fullName>ASI_MFM_CAP_HK_Set_CAP_Payment_Standard</fullName>
        <field>RecordTypeId</field>
        <lookupValue>ASI_MFM_CAP_HK_Payment</lookupValue>
        <lookupValueType>RecordType</lookupValueType>
        <name>Set CAP HK Payment Standard</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>LookupValue</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>ASI_MFM_CAP_HK_Set_Payment_Read</fullName>
        <field>RecordTypeId</field>
        <lookupValue>ASI_MFM_CAP_HK_Payment_Read_Only</lookupValue>
        <lookupValueType>RecordType</lookupValueType>
        <name>Set CAP HK Payment Read-Only</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>LookupValue</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>ASI_MFM_CAP_Payment_Sys_Reject</fullName>
        <field>ASI_MFM_Sys_Rejected__c</field>
        <literalValue>1</literalValue>
        <name>Set CAP Payment Sys Reject</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Literal</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>ASI_MFM_CAP_SG_Set_CAP_SG_Payment_Read</fullName>
        <field>RecordTypeId</field>
        <lookupValue>ASI_MFM_CAP_SG_Payment_Read_Only</lookupValue>
        <lookupValueType>RecordType</lookupValueType>
        <name>Set CAP SG Payment Read-Only</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>LookupValue</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>ASI_MFM_CAP_SG_Set_CAP_SG_Payment_Std</fullName>
        <field>RecordTypeId</field>
        <lookupValue>ASI_MFM_CAP_SG_Payment</lookupValue>
        <lookupValueType>RecordType</lookupValueType>
        <name>Set CAP SG Payment Standard</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>LookupValue</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>ASI_MFM_CAP_Set_CAP_Payment_Read_Only</fullName>
        <field>RecordTypeId</field>
        <lookupValue>ASI_MFM_CAP_Payment_Read_Only</lookupValue>
        <lookupValueType>RecordType</lookupValueType>
        <name>Set CAP Payment Read-Only</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>LookupValue</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>ASI_MFM_CAP_Set_CAP_Payment_Standard</fullName>
        <field>RecordTypeId</field>
        <lookupValue>ASI_MFM_CAP_Payment</lookupValue>
        <lookupValueType>RecordType</lookupValueType>
        <name>Set CAP Payment Standard</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>LookupValue</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>ASI_MFM_CAP_Set_Payment_Type_CAPEX</fullName>
        <field>ASI_MFM_Payment_Type__c</field>
        <literalValue>CAPEX</literalValue>
        <name>ASI MFM CAP Set Payment Type CAPEX</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Literal</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>ASI_MFM_CAP_Set_Payment_Type_OPEX</fullName>
        <field>ASI_MFM_Payment_Type__c</field>
        <literalValue>OPEX</literalValue>
        <name>ASI MFM CAP Set Payment Type OPEX</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Literal</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>ASI_MFM_CAP_TH_Set_CAP_TH_Payment_Read</fullName>
        <field>RecordTypeId</field>
        <lookupValue>ASI_MFM_CAP_TH_Payment_Read_Only</lookupValue>
        <lookupValueType>RecordType</lookupValueType>
        <name>Set CAP TH Payment Read-Only</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>LookupValue</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>ASI_MFM_CAP_TH_Set_CAP_TH_Payment_Std</fullName>
        <field>RecordTypeId</field>
        <lookupValue>ASI_MFM_CAP_TH_Payment</lookupValue>
        <lookupValueType>RecordType</lookupValueType>
        <name>Set CAP TH Payment Standard</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>LookupValue</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>ASI_MFM_CAP_TW_Set_CAP_Payment_Read_Only</fullName>
        <field>RecordTypeId</field>
        <lookupValue>ASI_MFM_CAP_TW_Payment_Read_Only</lookupValue>
        <lookupValueType>RecordType</lookupValueType>
        <name>Set CAP TW Payment Read-Only</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>LookupValue</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>ASI_MFM_CAP_TW_Set_CAP_Payment_Standard</fullName>
        <field>RecordTypeId</field>
        <lookupValue>ASI_MFM_CAP_TW_Payment</lookupValue>
        <lookupValueType>RecordType</lookupValueType>
        <name>Set CAP TW Payment Standard</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>LookupValue</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>ASI_MFM_CAP_Update_GL_Date_to_Today</fullName>
        <field>ASI_MFM_G_L_Date__c</field>
        <formula>Today()</formula>
        <name>Update GL Date to Today</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Formula</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>ASI_MFM_CN_Clear_Next_Approver</fullName>
        <field>ASI_MFM_CN_Next_Approver_ID__c</field>
        <name>Clear Next Approver</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Null</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>ASI_MFM_CN_Copy_App_10_to_Next_Approver</fullName>
        <field>ASI_MFM_CN_Next_Approver_ID__c</field>
        <formula>ASI_MFM_Sys_Approver_10__c</formula>
        <name>Copy Approver 10 to Next Approver</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Formula</operation>
        <protected>false</protected>
        <reevaluateOnChange>true</reevaluateOnChange>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>ASI_MFM_CN_Copy_App_1_to_Next_Approver</fullName>
        <field>ASI_MFM_CN_Next_Approver_ID__c</field>
        <formula>ASI_MFM_Sys_Approver_1__c</formula>
        <name>Copy Approver 1 to Next Approver</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Formula</operation>
        <protected>false</protected>
        <reevaluateOnChange>true</reevaluateOnChange>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>ASI_MFM_CN_Copy_App_2_to_Next_Approver</fullName>
        <field>ASI_MFM_CN_Next_Approver_ID__c</field>
        <formula>ASI_MFM_Sys_Approver_2__c</formula>
        <name>Copy Approver 2 to Next Approver</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Formula</operation>
        <protected>false</protected>
        <reevaluateOnChange>true</reevaluateOnChange>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>ASI_MFM_CN_Copy_App_3_to_Next_Approver</fullName>
        <field>ASI_MFM_CN_Next_Approver_ID__c</field>
        <formula>ASI_MFM_Sys_Approver_3__c</formula>
        <name>Copy Approver 3 to Next Approver</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Formula</operation>
        <protected>false</protected>
        <reevaluateOnChange>true</reevaluateOnChange>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>ASI_MFM_CN_Copy_App_4_to_Next_Approver</fullName>
        <field>ASI_MFM_CN_Next_Approver_ID__c</field>
        <formula>ASI_MFM_Sys_Approver_4__c</formula>
        <name>Copy Approver 4 to Next Approver</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Formula</operation>
        <protected>false</protected>
        <reevaluateOnChange>true</reevaluateOnChange>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>ASI_MFM_CN_Copy_App_5_to_Next_Approver</fullName>
        <field>ASI_MFM_CN_Next_Approver_ID__c</field>
        <formula>ASI_MFM_Sys_Approver_5__c</formula>
        <name>Copy Approver 5 to Next Approver</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Formula</operation>
        <protected>false</protected>
        <reevaluateOnChange>true</reevaluateOnChange>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>ASI_MFM_CN_Copy_App_6_to_Next_Approver</fullName>
        <field>ASI_MFM_CN_Next_Approver_ID__c</field>
        <formula>ASI_MFM_Sys_Approver_6__c</formula>
        <name>Copy Approver 6 to Next Approver</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Formula</operation>
        <protected>false</protected>
        <reevaluateOnChange>true</reevaluateOnChange>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>ASI_MFM_CN_Copy_App_7_to_Next_Approver</fullName>
        <field>ASI_MFM_CN_Next_Approver_ID__c</field>
        <formula>ASI_MFM_SYS_Approver_7__c</formula>
        <name>Copy Approver 7 to Next Approver</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Formula</operation>
        <protected>false</protected>
        <reevaluateOnChange>true</reevaluateOnChange>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>ASI_MFM_CN_Copy_App_8_to_Next_Approver</fullName>
        <field>ASI_MFM_CN_Next_Approver_ID__c</field>
        <formula>ASI_MFM_SYS_Approver_8__c</formula>
        <name>Copy Approver 8 to Next Approver</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Formula</operation>
        <protected>false</protected>
        <reevaluateOnChange>true</reevaluateOnChange>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>ASI_MFM_CN_Copy_App_9_to_Next_Approver</fullName>
        <field>ASI_MFM_CN_Next_Approver_ID__c</field>
        <formula>ASI_MFM_SYS_Approver_9__c</formula>
        <name>Copy Approver 9 to Next Approver</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Formula</operation>
        <protected>false</protected>
        <reevaluateOnChange>true</reevaluateOnChange>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>ASI_MFM_CN_Copy_Payment</fullName>
        <field>ASI_MFM_CN_Payment_Original_Amount__c</field>
        <formula>ASI_MFM_Payment_Amount__c</formula>
        <name>Copy Payment Amount after Approval</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Formula</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>ASI_MFM_CN_Reset_Approval_Count</fullName>
        <field>ASI_MFM_Approval_Count__c</field>
        <formula>1</formula>
        <name>CN Reset Approval Count</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Formula</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>ASI_MFM_CN_SetApproval_Count</fullName>
        <field>ASI_MFM_Approval_Count__c</field>
        <formula>BLANKVALUE( ASI_MFM_Approval_Count__c, 0) + 1</formula>
        <name>CN SetApproval Count</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Formula</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>ASI_MFM_CN_Set_Payment_Read_Only_CN</fullName>
        <field>RecordTypeId</field>
        <lookupValue>ASI_MFM_CN_Payment_Read_Only</lookupValue>
        <lookupValueType>RecordType</lookupValueType>
        <name>Set Payment Read-Only (CN)</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>LookupValue</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>ASI_MFM_CN_Supplier_Email</fullName>
        <field>ASI_MFM_Supplier_Email__c</field>
        <formula>ASI_MFM_Supplier_Name__r.ASI_LUX_Email_Business__c</formula>
        <name>CN Supplier Email</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Formula</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>ASI_MFM_CN_Uncheck_Return_Flag</fullName>
        <field>ASI_MFM_CN_Return_Flag__c</field>
        <literalValue>0</literalValue>
        <name>Uncheck Return Flag</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Literal</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>ASI_MFM_Check_Approved_Flag</fullName>
        <field>ASI_MFM_Approved__c</field>
        <literalValue>1</literalValue>
        <name>Check Approved Flag</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Literal</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>ASI_MFM_Clear_Sys_Approver_1</fullName>
        <field>ASI_MFM_Sys_Approver_1__c</field>
        <name>Clear Sys Approver 1</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>LookupValue</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>ASI_MFM_GF_Payment_GLDate_FieldUpdate</fullName>
        <field>ASI_MFM_G_L_Date__c</field>
        <formula>Today()</formula>
        <name>ASI_MFM_GF_Payment_GLDate_FieldUpdate</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Formula</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>ASI_MFM_GF_Set_Payment_RT_ReadOnly</fullName>
        <field>RecordTypeId</field>
        <lookupValue>ASI_MFM_GF_Payment_Read_Only</lookupValue>
        <lookupValueType>RecordType</lookupValueType>
        <name>ASI MFM GF Set Payment RT ReadOnly</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>LookupValue</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>ASI_MFM_HK_Payment_Update_Prefix_Departm</fullName>
        <field>ASI_MFM_Prefix_Department__c</field>
        <formula>TEXT(ASI_MFM_Prefix__r.ASI_MFM_Prefix_Department__c)</formula>
        <name>ASI_MFM_HK_Payment_Update_Prefix_Departm</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Formula</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>ASI_MFM_HK_Set_Payment_ReadOnly</fullName>
        <field>RecordTypeId</field>
        <lookupValue>ASI_MFM_HK_Payment_Read_Only</lookupValue>
        <lookupValueType>RecordType</lookupValueType>
        <name>ASI MFM HK Set Payment ReadOnly</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>LookupValue</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>ASI_MFM_HK_Set_Payment_Standard</fullName>
        <field>RecordTypeId</field>
        <lookupValue>ASI_MFM_HK_Payment</lookupValue>
        <lookupValueType>RecordType</lookupValueType>
        <name>ASI MFM HK Set Payment Standard</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>LookupValue</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>ASI_MFM_JP_Set_Payment_Read_Only</fullName>
        <field>RecordTypeId</field>
        <lookupValue>ASI_MFM_JP_Payment_Read_Only</lookupValue>
        <lookupValueType>RecordType</lookupValueType>
        <name>ASI MFM JP Set Payment Read-Only</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>LookupValue</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>ASI_MFM_JP_Set_Payment_Standard</fullName>
        <field>RecordTypeId</field>
        <lookupValue>ASI_MFM_JP_Payment</lookupValue>
        <lookupValueType>RecordType</lookupValueType>
        <name>ASI MFM JP Set Payment Standard</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>LookupValue</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>ASI_MFM_KR_CashOut_Offset_SetVATAmt</fullName>
        <field>ASI_MFM_KR_TotalPayAmtIncludeVAT__c</field>
        <formula>ASI_MFM_Payment_Amount__c</formula>
        <name>ASI_MFM_KR_CashOut_Offset_SetVATAmt</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Formula</operation>
        <protected>false</protected>
        <reevaluateOnChange>true</reevaluateOnChange>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>ASI_MFM_KR_Set_Payment_Read_Only</fullName>
        <field>RecordTypeId</field>
        <lookupValue>ASI_MFM_KR_Payment_Read_Only</lookupValue>
        <lookupValueType>RecordType</lookupValueType>
        <name>ASI MFM KR Set Payment Read-Only</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>LookupValue</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>ASI_MFM_KR_Set_Payment_Standard</fullName>
        <field>RecordTypeId</field>
        <lookupValue>ASI_MFM_KR_Payment</lookupValue>
        <lookupValueType>RecordType</lookupValueType>
        <name>ASI MFM KR Set Payment Standard</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>LookupValue</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>ASI_MFM_MY_Set_Payment_Read_Only</fullName>
        <field>RecordTypeId</field>
        <lookupValue>ASI_MFM_MY_Payment_Read_Only</lookupValue>
        <lookupValueType>RecordType</lookupValueType>
        <name>ASI MFM MY Set Payment Read-Only</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>LookupValue</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>ASI_MFM_MY_Set_Payment_Standard</fullName>
        <field>RecordTypeId</field>
        <lookupValue>ASI_MFM_MY_Payment</lookupValue>
        <lookupValueType>RecordType</lookupValueType>
        <name>ASI MFM MY Set Payment Standard</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>LookupValue</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>ASI_MFM_PH_DF_Set_Payment_Read_Only</fullName>
        <field>RecordTypeId</field>
        <lookupValue>ASI_MFM_PH_DF_Payment_Read_Only</lookupValue>
        <lookupValueType>RecordType</lookupValueType>
        <name>ASI MFM PH DF Set Payment Read-Only</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>LookupValue</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>ASI_MFM_PH_DF_Set_Payment_Standard</fullName>
        <field>RecordTypeId</field>
        <lookupValue>ASI_MFM_PH_DF_Payment</lookupValue>
        <lookupValueType>RecordType</lookupValueType>
        <name>ASI MFM PH DF Set Payment Standard</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>LookupValue</operation>
        <protected>false</protected>
        <reevaluateOnChange>true</reevaluateOnChange>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>ASI_MFM_PH_DP_Set_Payment_Read_Only</fullName>
        <field>RecordTypeId</field>
        <lookupValue>ASI_MFM_PH_DP_Payment_Read_Only</lookupValue>
        <lookupValueType>RecordType</lookupValueType>
        <name>ASI MFM PH DP Set Payment Read-Only</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>LookupValue</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>ASI_MFM_PH_DP_Set_Payment_Standard</fullName>
        <field>RecordTypeId</field>
        <lookupValue>ASI_MFM_PH_DP_Payment</lookupValue>
        <lookupValueType>RecordType</lookupValueType>
        <name>ASI MFM PH DP Set Payment Standard</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>LookupValue</operation>
        <protected>false</protected>
        <reevaluateOnChange>true</reevaluateOnChange>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>ASI_MFM_Payment_GL_Date_Update</fullName>
        <field>ASI_MFM_G_L_Date__c</field>
        <formula>TODAY()</formula>
        <name>ASI_MFM_Payment_GL_Date_Update</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Formula</operation>
        <protected>false</protected>
        <reevaluateOnChange>true</reevaluateOnChange>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>ASI_MFM_Payment_PO_Status_To_Final</fullName>
        <field>ASI_MFM_Status__c</field>
        <literalValue>Final</literalValue>
        <name>ASI MFM Update Payment Status To Final</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Literal</operation>
        <protected>false</protected>
        <reevaluateOnChange>true</reevaluateOnChange>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>ASI_MFM_SC_Set_Payment_Standard</fullName>
        <field>RecordTypeId</field>
        <lookupValue>ASI_MFM_SC_Payment</lookupValue>
        <lookupValueType>RecordType</lookupValueType>
        <name>Set SC Payment Standard</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>LookupValue</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>ASI_MFM_SG_Set_Payment_Read_Only</fullName>
        <field>RecordTypeId</field>
        <lookupValue>ASI_MFM_SG_Payment_Read_Only</lookupValue>
        <lookupValueType>RecordType</lookupValueType>
        <name>ASI MFM SG Set Payment Read-Only</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>LookupValue</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>ASI_MFM_SG_Set_Payment_Send_Approval</fullName>
        <field>ASI_MFM_Send_Approval_Email__c</field>
        <literalValue>0</literalValue>
        <name>Set Payment Send Approval Email To False</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Literal</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>ASI_MFM_Set_Approver_Email_Address</fullName>
        <field>ASI_MFM_Sys_Approver_Email_Address__c</field>
        <formula>$User.Email</formula>
        <name>Set Approver Email Address</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Formula</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>ASI_MFM_Set_Exceed_Tolerance_Limit_False</fullName>
        <field>ASI_MFM_Exceed_Tolerance_Limit__c</field>
        <literalValue>0</literalValue>
        <name>Set Exceed Tolerance Limit False</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Literal</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>ASI_MFM_Set_Exceed_Tolerance_Limit_True</fullName>
        <field>ASI_MFM_Exceed_Tolerance_Limit__c</field>
        <literalValue>1</literalValue>
        <name>Set Exceed Tolerance Limit True</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Literal</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>ASI_MFM_Set_Payment_External_ID</fullName>
        <field>ASI_MFM_Payment_External_ID__c</field>
        <formula>Name</formula>
        <name>Set Payment External ID</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Formula</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>ASI_MFM_Set_Payment_Read_Only</fullName>
        <field>RecordTypeId</field>
        <lookupValue>ASI_MFM_TW_Payment_Read_Only</lookupValue>
        <lookupValueType>RecordType</lookupValueType>
        <name>Set Payment Read-Only</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>LookupValue</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>ASI_MFM_Set_Payment_Standard</fullName>
        <field>RecordTypeId</field>
        <lookupValue>ASI_MFM_TW_Payment</lookupValue>
        <lookupValueType>RecordType</lookupValueType>
        <name>Set Payment Standard</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>LookupValue</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>ASI_MFM_Set_Payment_Status_To_Draft</fullName>
        <field>ASI_MFM_Status__c</field>
        <literalValue>Draft</literalValue>
        <name>Set Payment Status To Draft</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Literal</operation>
        <protected>false</protected>
        <reevaluateOnChange>true</reevaluateOnChange>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>ASI_MFM_Set_Payment_Status_To_Final</fullName>
        <field>ASI_MFM_Status__c</field>
        <literalValue>Final</literalValue>
        <name>Set Payment Status To Final</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Literal</operation>
        <protected>false</protected>
        <reevaluateOnChange>true</reevaluateOnChange>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>ASI_MFM_Set_Payment_Status_To_Rejected</fullName>
        <field>ASI_MFM_Status__c</field>
        <literalValue>Rejected</literalValue>
        <name>ASI MFM Set Payment Status To Rejected</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Literal</operation>
        <protected>false</protected>
        <reevaluateOnChange>true</reevaluateOnChange>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>ASI_MFM_Set_Payment_Status_To_Submitted</fullName>
        <field>ASI_MFM_Status__c</field>
        <literalValue>Submitted</literalValue>
        <name>Set Payment Status To Submitted</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Literal</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>ASI_MFM_Set_Payment_Status_to_Approved</fullName>
        <description>ASI MFM Update Payment Status to Approved</description>
        <field>ASI_MFM_Status__c</field>
        <literalValue>Approved</literalValue>
        <name>ASI MFM Set Payment Status to Approved</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Literal</operation>
        <protected>false</protected>
        <reevaluateOnChange>true</reevaluateOnChange>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>ASI_MFM_Set_SC_Payment_ReadOnly</fullName>
        <field>RecordTypeId</field>
        <lookupValue>ASI_MFM_SC_Payment_Read_Only</lookupValue>
        <lookupValueType>RecordType</lookupValueType>
        <name>Set SC Payment Read-Only</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>LookupValue</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>ASI_MFM_Set_SG_ETL_Date</fullName>
        <field>ASI_MFM_ETL_Date__c</field>
        <formula>NOW()</formula>
        <name>ASI_MFM_Set_SG_ETL_Date</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Formula</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>ASI_MFM_Set_SendApprovalEmailTo_False</fullName>
        <description>Send Approval Email</description>
        <field>ASI_MFM_Send_Approval_Email__c</field>
        <literalValue>0</literalValue>
        <name>Set SendApprovalEmailTo False</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Literal</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>ASI_MFM_Set_Submitter_Email_Address</fullName>
        <field>ASI_MFM_Sys_Submitter_Email_Address__c</field>
        <formula>$User.Email</formula>
        <name>Set Submitter Email Address</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Formula</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>ASI_MFM_Set_Sys_Allow_Submit_Aprv_False</fullName>
        <field>ASI_MFM_Sys_Allow_Submit_Approval__c</field>
        <literalValue>0</literalValue>
        <name>Set Sys Allow Submit Approval False</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Literal</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>ASI_MFM_Set_TH_ETL_Date</fullName>
        <field>ASI_MFM_ETL_Date__c</field>
        <formula>NOW()</formula>
        <name>ASI_MFM_Set_TH_ETL_Date</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Formula</operation>
        <protected>false</protected>
        <reevaluateOnChange>true</reevaluateOnChange>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>ASI_MFM_TH_Set_Payment_Read_Only</fullName>
        <field>RecordTypeId</field>
        <lookupValue>ASI_MFM_TH_Payment_Read_Only</lookupValue>
        <lookupValueType>RecordType</lookupValueType>
        <name>ASI MFM TH Set Payment Read-Only</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>LookupValue</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>ASI_MFM_TH_Set_Payment_Standard</fullName>
        <field>RecordTypeId</field>
        <lookupValue>ASI_MFM_TH_Payment</lookupValue>
        <lookupValueType>RecordType</lookupValueType>
        <name>ASI MFM TH Set Payment Standard</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>LookupValue</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>ASI_MFM_Uncheck_Approved_Flag</fullName>
        <field>ASI_MFM_Approved__c</field>
        <literalValue>0</literalValue>
        <name>Uncheck Approved Flag</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Literal</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>ASI_MFM_Uncheck_ETL_Flag</fullName>
        <field>ASI_MFM_ETL__c</field>
        <literalValue>0</literalValue>
        <name>Uncheck ETL Flag</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Literal</operation>
        <protected>false</protected>
    </fieldUpdates>
    <rules>
        <fullName>ASI_MFM_CAP_Finalize_Payment</fullName>
        <actions>
            <name>ASI_MFM_CAP_Set_CAP_Payment_Read_Only</name>
            <type>FieldUpdate</type>
        </actions>
        <active>true</active>
        <criteriaItems>
            <field>ASI_MFM_Payment__c.ASI_MFM_Status__c</field>
            <operation>equals</operation>
            <value>Final,Complete</value>
        </criteriaItems>
        <criteriaItems>
            <field>ASI_MFM_Payment__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>CAP Payment</value>
        </criteriaItems>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
    </rules>
    <rules>
        <fullName>ASI_MFM_CAP_Finance_Reject_Payment</fullName>
        <actions>
            <name>ASI_MFM_CAP_Payment_Rejected_Notification_Email_Alert</name>
            <type>Alert</type>
        </actions>
        <active>true</active>
        <formula>(ISPICKVAL(PRIORVALUE(ASI_MFM_Status__c),&apos;Final&apos;) || ISPICKVAL(PRIORVALUE(ASI_MFM_Status__c),&apos;Finance Verfied&apos;))  &amp;&amp; ISPICKVAL(ASI_MFM_Status__c, &apos;Draft&apos;)  &amp;&amp; OR( RecordType.DeveloperName = &apos;ASI_MFM_CAP_Payment&apos;,RecordType.DeveloperName =&apos;ASI_MFM_CAP_Payment_Read_Only&apos;)</formula>
        <triggerType>onAllChanges</triggerType>
    </rules>
    <rules>
        <fullName>ASI_MFM_CAP_Free_Payment</fullName>
        <actions>
            <name>ASI_MFM_CAP_Set_CAP_Payment_Standard</name>
            <type>FieldUpdate</type>
        </actions>
        <active>true</active>
        <criteriaItems>
            <field>ASI_MFM_Payment__c.ASI_MFM_Status__c</field>
            <operation>equals</operation>
            <value>Draft</value>
        </criteriaItems>
        <criteriaItems>
            <field>ASI_MFM_Payment__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>CAP Payment Read-Only</value>
        </criteriaItems>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
    </rules>
    <rules>
        <fullName>ASI_MFM_CAP_GL_Date_Convert_To_FinanceVerified</fullName>
        <actions>
            <name>ASI_MFM_CAP_Update_GL_Date_to_Today</name>
            <type>FieldUpdate</type>
        </actions>
        <active>true</active>
        <criteriaItems>
            <field>ASI_MFM_Payment__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>CAP Payment Read-Only</value>
        </criteriaItems>
        <criteriaItems>
            <field>ASI_MFM_Payment__c.ASI_MFM_Status__c</field>
            <operation>equals</operation>
            <value>Finance Verified</value>
        </criteriaItems>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
    </rules>
    <rules>
        <fullName>ASI_MFM_CAP_HK_Exceed_Tolerance_Limit</fullName>
        <actions>
            <name>ASI_MFM_Set_Exceed_Tolerance_Limit_True</name>
            <type>FieldUpdate</type>
        </actions>
        <active>true</active>
        <formula>AND(      CONTAINS(RecordType.DeveloperName, &quot;ASI_MFM_CAP_HK&quot;),      NOT(ASI_MFM_Exceed_Tolerance_Limit__c),      ABS(ASI_MFM_Goods_In_Transit_Amount_SFDC__c - ASI_MFM_Goods_In_Transit_Amount__c) &gt; ASI_MFM_Tolerance_Limit__c )</formula>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
    </rules>
    <rules>
        <fullName>ASI_MFM_CAP_HK_Free_Payment</fullName>
        <actions>
            <name>ASI_MFM_CAP_HK_Set_CAP_Payment_Standard</name>
            <type>FieldUpdate</type>
        </actions>
        <active>true</active>
        <formula>AND(    CONTAINS(RecordType.DeveloperName , &quot;ASI_MFM_CAP_HK&quot;),    ISPICKVAL(PRIORVALUE(ASI_MFM_Status__c), &quot;Approved&quot;),    ISPICKVAL(ASI_MFM_Status__c, &quot;Draft&quot;) )</formula>
        <triggerType>onAllChanges</triggerType>
    </rules>
    <rules>
        <fullName>ASI_MFM_CAP_HK_Within_Tolerance_Limit</fullName>
        <actions>
            <name>ASI_MFM_Set_Exceed_Tolerance_Limit_False</name>
            <type>FieldUpdate</type>
        </actions>
        <active>true</active>
        <formula>AND(      CONTAINS(RecordType.DeveloperName, &quot;ASI_MFM_CAP_HK&quot;),      ASI_MFM_Exceed_Tolerance_Limit__c,      ABS(ASI_MFM_Goods_In_Transit_Amount_SFDC__c - ASI_MFM_Goods_In_Transit_Amount__c) &lt;= ASI_MFM_Tolerance_Limit__c )</formula>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
    </rules>
    <rules>
        <fullName>ASI_MFM_CAP_SG_Finalize_Payment</fullName>
        <actions>
            <name>ASI_MFM_CAP_SG_Set_CAP_SG_Payment_Read</name>
            <type>FieldUpdate</type>
        </actions>
        <active>true</active>
        <criteriaItems>
            <field>ASI_MFM_Payment__c.ASI_MFM_Status__c</field>
            <operation>equals</operation>
            <value>Final</value>
        </criteriaItems>
        <criteriaItems>
            <field>ASI_MFM_Payment__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>OPEX SG Payment</value>
        </criteriaItems>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
    </rules>
    <rules>
        <fullName>ASI_MFM_CAP_SG_Free_Payment</fullName>
        <actions>
            <name>ASI_MFM_CAP_SG_Set_CAP_SG_Payment_Std</name>
            <type>FieldUpdate</type>
        </actions>
        <active>true</active>
        <criteriaItems>
            <field>ASI_MFM_Payment__c.ASI_MFM_Status__c</field>
            <operation>equals</operation>
            <value>Draft</value>
        </criteriaItems>
        <criteriaItems>
            <field>ASI_MFM_Payment__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>CAP SG Payment Read-Only</value>
        </criteriaItems>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
    </rules>
    <rules>
        <fullName>ASI_MFM_CAP_Send_Payment_Rejection_Notification_Email</fullName>
        <actions>
            <name>ASI_MFM_CAP_Payment_Rejected_Notification_Email_Alert</name>
            <type>Alert</type>
        </actions>
        <active>true</active>
        <formula>ISPICKVAL(ASI_MFM_Status__c, &apos;Draft&apos;) &amp;&amp; OR(ISPICKVAL(PRIORVALUE( ASI_MFM_Status__c ), &apos;Submitted&apos;),ISPICKVAL(PRIORVALUE( ASI_MFM_Status__c ), &apos;Final&apos;)) &amp;&amp; OR(RecordType.DeveloperName=&apos;ASI_MFM_CAP_Payment&apos;, RecordType.DeveloperName=&apos;ASI_MFM_CAP_Payment_Read_Only&apos;, RecordType.DeveloperName=&apos;ASI_MFM_CAP_T_E_Payment&apos;)</formula>
        <triggerType>onAllChanges</triggerType>
    </rules>
    <rules>
        <fullName>ASI_MFM_CAP_Set_Type_CAPEX</fullName>
        <actions>
            <name>ASI_MFM_CAP_Set_Payment_Type_CAPEX</name>
            <type>FieldUpdate</type>
        </actions>
        <active>true</active>
        <formula>ISCHANGED(ASI_MFM_Plan__c) &amp;&amp;  ISPICKVAL( ASI_MFM_Payment_Type__c , &apos;OPEX&apos;)  &amp;&amp; ISPICKVAL(ASI_MFM_Plan__r.ASI_MFM_Plan_Type__c , &apos;CAPEX&apos;)  &amp;&amp;  RecordType.DeveloperName = &apos;ASI_MFM_CAP_Payment&apos; &amp;&amp;  ASI_MFM_OCR__c</formula>
        <triggerType>onAllChanges</triggerType>
    </rules>
    <rules>
        <fullName>ASI_MFM_CAP_Set_Type_OPEX</fullName>
        <actions>
            <name>ASI_MFM_CAP_Set_Payment_Type_OPEX</name>
            <type>FieldUpdate</type>
        </actions>
        <active>true</active>
        <formula>ISCHANGED(ASI_MFM_Plan__c) &amp;&amp; ISPICKVAL( ASI_MFM_Payment_Type__c , &apos;CAPEX&apos;) &amp;&amp; ISPICKVAL(ASI_MFM_Plan__r.ASI_MFM_Plan_Type__c , &apos;OPEX&apos;) &amp;&amp;  RecordType.DeveloperName = &apos;ASI_MFM_CAP_Payment&apos; &amp;&amp;  ASI_MFM_OCR__c</formula>
        <triggerType>onAllChanges</triggerType>
    </rules>
    <rules>
        <fullName>ASI_MFM_CAP_TH_Finalize_Payment</fullName>
        <actions>
            <name>ASI_MFM_CAP_TH_Set_CAP_TH_Payment_Read</name>
            <type>FieldUpdate</type>
        </actions>
        <active>true</active>
        <criteriaItems>
            <field>ASI_MFM_Payment__c.ASI_MFM_Status__c</field>
            <operation>equals</operation>
            <value>Final</value>
        </criteriaItems>
        <criteriaItems>
            <field>ASI_MFM_Payment__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>OPEX TH Payment</value>
        </criteriaItems>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
    </rules>
    <rules>
        <fullName>ASI_MFM_CAP_TH_Free_Payment</fullName>
        <actions>
            <name>ASI_MFM_CAP_TH_Set_CAP_TH_Payment_Std</name>
            <type>FieldUpdate</type>
        </actions>
        <active>true</active>
        <criteriaItems>
            <field>ASI_MFM_Payment__c.ASI_MFM_Status__c</field>
            <operation>equals</operation>
            <value>Draft</value>
        </criteriaItems>
        <criteriaItems>
            <field>ASI_MFM_Payment__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>OPEX TH Payment Read-Only</value>
        </criteriaItems>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
    </rules>
    <rules>
        <fullName>ASI_MFM_CAP_TH_Notify_Finance</fullName>
        <actions>
            <name>ASI_MFM_CAP_TH_Payment_Approval_Request_Email_Alert</name>
            <type>Alert</type>
        </actions>
        <active>true</active>
        <criteriaItems>
            <field>ASI_MFM_Payment__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>OPEX TH Payment</value>
        </criteriaItems>
        <triggerType>onCreateOnly</triggerType>
    </rules>
    <rules>
        <fullName>ASI_MFM_CAP_TW_Finalize_Payment</fullName>
        <actions>
            <name>ASI_MFM_CAP_TW_Set_CAP_Payment_Read_Only</name>
            <type>FieldUpdate</type>
        </actions>
        <active>true</active>
        <criteriaItems>
            <field>ASI_MFM_Payment__c.ASI_MFM_Status__c</field>
            <operation>equals</operation>
            <value>Final,Complete</value>
        </criteriaItems>
        <criteriaItems>
            <field>ASI_MFM_Payment__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>CAP TW Payment</value>
        </criteriaItems>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
    </rules>
    <rules>
        <fullName>ASI_MFM_CAP_TW_Free_Payment</fullName>
        <actions>
            <name>ASI_MFM_CAP_TW_Set_CAP_Payment_Standard</name>
            <type>FieldUpdate</type>
        </actions>
        <active>true</active>
        <criteriaItems>
            <field>ASI_MFM_Payment__c.ASI_MFM_Status__c</field>
            <operation>equals</operation>
            <value>Draft</value>
        </criteriaItems>
        <criteriaItems>
            <field>ASI_MFM_Payment__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>CAP TW Payment Read-Only</value>
        </criteriaItems>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
    </rules>
    <rules>
        <fullName>ASI_MFM_CN_CashOut</fullName>
        <actions>
            <name>ASI_MFM_CN_CashOutAlert</name>
            <type>Alert</type>
        </actions>
        <active>true</active>
        <criteriaItems>
            <field>ASI_MFM_Payment__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>CN Payment,CN Payment Read-Only</value>
        </criteriaItems>
        <criteriaItems>
            <field>ASI_MFM_Payment__c.ASI_MFM_PaymentDate__c</field>
            <operation>notEqual</operation>
        </criteriaItems>
        <criteriaItems>
            <field>ASI_MFM_Payment__c.ASI_MFM_Supplier_Email__c</field>
            <operation>notEqual</operation>
        </criteriaItems>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
    </rules>
    <rules>
        <fullName>ASI_MFM_CN_Check_If_Next_Approver_Finance</fullName>
        <actions>
            <name>ASI_MFM_CN_Payment_Submitted_to_Finance_Notification</name>
            <type>Alert</type>
        </actions>
        <active>true</active>
        <formula>AND( ASI_MFM_CN_Finance__c =  ASI_MFM_CN_Next_Approver_ID__c,    CONTAINS(RecordType.DeveloperName, &apos;ASI_MFM_CN&apos;)  )</formula>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
    </rules>
    <rules>
        <fullName>ASI_MFM_CN_Send_Budget_Owner_Notification</fullName>
        <actions>
            <name>ASI_MFM_CN_Send_notification_to_budget_owner_of_Payment</name>
            <type>Alert</type>
        </actions>
        <active>true</active>
        <formula>AND(ASI_MFM_Budget_Owner__c != OwnerId, ISPICKVAL( ASI_MFM_Status__c , &apos;Submitted&apos;), ISCHANGED(ASI_MFM_Status__c) ,  CONTAINS(RecordType.DeveloperName, &apos;ASI_MFM_CN&apos; ))</formula>
        <triggerType>onAllChanges</triggerType>
    </rules>
    <rules>
        <fullName>ASI_MFM_CN_SupplierEmail</fullName>
        <actions>
            <name>ASI_MFM_CN_Supplier_Email</name>
            <type>FieldUpdate</type>
        </actions>
        <active>true</active>
        <criteriaItems>
            <field>ASI_MFM_Payment__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>CN Payment,CN Payment Read-Only</value>
        </criteriaItems>
        <triggerType>onAllChanges</triggerType>
    </rules>
    <rules>
        <fullName>ASI_MFM_Finalize_Payment</fullName>
        <actions>
            <name>ASI_MFM_Set_Payment_Read_Only</name>
            <type>FieldUpdate</type>
        </actions>
        <active>true</active>
        <criteriaItems>
            <field>ASI_MFM_Payment__c.ASI_MFM_Status__c</field>
            <operation>equals</operation>
            <value>Final,Complete</value>
        </criteriaItems>
        <criteriaItems>
            <field>ASI_MFM_Payment__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>TW Payment</value>
        </criteriaItems>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
    </rules>
    <rules>
        <fullName>ASI_MFM_Free_Payment</fullName>
        <actions>
            <name>ASI_MFM_Set_Payment_Standard</name>
            <type>FieldUpdate</type>
        </actions>
        <active>true</active>
        <criteriaItems>
            <field>ASI_MFM_Payment__c.ASI_MFM_Status__c</field>
            <operation>equals</operation>
            <value>Draft</value>
        </criteriaItems>
        <criteriaItems>
            <field>ASI_MFM_Payment__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>TW Payment Read-Only</value>
        </criteriaItems>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
    </rules>
    <rules>
        <fullName>ASI_MFM_GF_Direct_Payment_Notify_Fin</fullName>
        <actions>
            <name>ASI_MFM_GF_Direct_Payment_Fin_Alert</name>
            <type>Alert</type>
        </actions>
        <active>false</active>
        <criteriaItems>
            <field>ASI_MFM_Payment__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>GF Payment Read-Only</value>
        </criteriaItems>
        <criteriaItems>
            <field>ASI_MFM_Payment__c.ASI_MFM_Status__c</field>
            <operation>equals</operation>
            <value>Final</value>
        </criteriaItems>
        <criteriaItems>
            <field>ASI_MFM_Payment__c.ASI_MFM_Is_Direct_Payment__c</field>
            <operation>equals</operation>
            <value>True</value>
        </criteriaItems>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
    </rules>
    <rules>
        <fullName>ASI_MFM_GF_Direct_Payment_Notify_Fin_V2</fullName>
        <active>true</active>
        <formula>AND (  RecordType.DeveloperName = &quot;ASI_MFM_GF_Payment_Read_Only&quot;,  ISPICKVAL( ASI_MFM_Status__c, &quot;Final&quot;),  ASI_MFM_Is_Direct_Payment__c = true,  ASI_MFM_Is_AMEX_Payment__c = false )</formula>
        <triggerType>onCreateOnly</triggerType>
        <workflowTimeTriggers>
            <actions>
                <name>ASI_MFM_GF_Direct_Payment_Fin_Alert</name>
                <type>Alert</type>
            </actions>
            <offsetFromField>ASI_MFM_Payment__c.ASI_MFM_Email_Time__c</offsetFromField>
            <timeLength>1</timeLength>
            <workflowTimeTriggerUnit>Hours</workflowTimeTriggerUnit>
        </workflowTimeTriggers>
    </rules>
    <rules>
        <fullName>ASI_MFM_GF_PaymenttInterfaceWarningRule</fullName>
        <active>true</active>
        <criteriaItems>
            <field>ASI_MFM_Payment__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>GF Payment Read-Only</value>
        </criteriaItems>
        <criteriaItems>
            <field>ASI_MFM_Payment__c.ASI_MFM_Status__c</field>
            <operation>equals</operation>
            <value>Final</value>
        </criteriaItems>
        <criteriaItems>
            <field>ASI_MFM_Payment__c.ASI_MFM_ETL__c</field>
            <operation>equals</operation>
            <value>False</value>
        </criteriaItems>
        <criteriaItems>
            <field>ASI_MFM_Payment__c.ASI_MFM_Is_AMEX_Payment__c</field>
            <operation>equals</operation>
            <value>False</value>
        </criteriaItems>
        <criteriaItems>
            <field>ASI_MFM_Payment__c.ASI_MFM_Invoice_Number__c</field>
            <operation>notContain</operation>
            <value>SYS_20</value>
        </criteriaItems>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
        <workflowTimeTriggers>
            <actions>
                <name>ASI_MFM_GF_PaymentInterfaceWarningAlert</name>
                <type>Alert</type>
            </actions>
            <timeLength>3</timeLength>
            <workflowTimeTriggerUnit>Days</workflowTimeTriggerUnit>
        </workflowTimeTriggers>
    </rules>
    <rules>
        <fullName>ASI_MFM_GF_Send_Payment_Reject_Notification_Email</fullName>
        <actions>
            <name>ASI_MFM_GF_Payment_Rejected_Email_Alert</name>
            <type>Alert</type>
        </actions>
        <active>true</active>
        <formula>ISPICKVAL(ASI_MFM_Status__c, &quot;Draft&quot;) &amp;&amp; ISPICKVAL(PRIORVALUE( ASI_MFM_Status__c ), &quot;Submitted&quot;) &amp;&amp; (  CONTAINS(RecordType.DeveloperName, &quot;ASI_MFM_GF&quot;))</formula>
        <triggerType>onAllChanges</triggerType>
    </rules>
    <rules>
        <fullName>ASI_MFM_HK_Finalize_Payment</fullName>
        <actions>
            <name>ASI_MFM_HK_Set_Payment_ReadOnly</name>
            <type>FieldUpdate</type>
        </actions>
        <active>true</active>
        <criteriaItems>
            <field>ASI_MFM_Payment__c.ASI_MFM_Status__c</field>
            <operation>equals</operation>
            <value>Final,Complete</value>
        </criteriaItems>
        <criteriaItems>
            <field>ASI_MFM_Payment__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>HK Payment</value>
        </criteriaItems>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
    </rules>
    <rules>
        <fullName>ASI_MFM_HK_Free_Payment</fullName>
        <actions>
            <name>ASI_MFM_HK_Set_Payment_Standard</name>
            <type>FieldUpdate</type>
        </actions>
        <active>true</active>
        <criteriaItems>
            <field>ASI_MFM_Payment__c.ASI_MFM_Status__c</field>
            <operation>equals</operation>
            <value>Draft</value>
        </criteriaItems>
        <criteriaItems>
            <field>ASI_MFM_Payment__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>HK Payment Read-Only</value>
        </criteriaItems>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
    </rules>
    <rules>
        <fullName>ASI_MFM_HK_Payment_Update_Prefix_Department%EF%BB%BF</fullName>
        <actions>
            <name>ASI_MFM_HK_Payment_Update_Prefix_Departm</name>
            <type>FieldUpdate</type>
        </actions>
        <active>true</active>
        <criteriaItems>
            <field>ASI_MFM_Payment__c.ASI_MFM_Prefix_Department__c</field>
            <operation>equals</operation>
        </criteriaItems>
        <criteriaItems>
            <field>ASI_MFM_Payment__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>HK Payment,HK Payment Read-Only</value>
        </criteriaItems>
        <triggerType>onAllChanges</triggerType>
    </rules>
    <rules>
        <fullName>ASI_MFM_JP_Finalize_Payment</fullName>
        <actions>
            <name>ASI_MFM_JP_Set_Payment_Read_Only</name>
            <type>FieldUpdate</type>
        </actions>
        <active>true</active>
        <criteriaItems>
            <field>ASI_MFM_Payment__c.ASI_MFM_Status__c</field>
            <operation>equals</operation>
            <value>Submitted,Final,Complete</value>
        </criteriaItems>
        <criteriaItems>
            <field>ASI_MFM_Payment__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>JP Payment</value>
        </criteriaItems>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
    </rules>
    <rules>
        <fullName>ASI_MFM_JP_Free_Payment</fullName>
        <actions>
            <name>ASI_MFM_JP_Set_Payment_Standard</name>
            <type>FieldUpdate</type>
        </actions>
        <active>true</active>
        <criteriaItems>
            <field>ASI_MFM_Payment__c.ASI_MFM_Status__c</field>
            <operation>equals</operation>
            <value>Draft</value>
        </criteriaItems>
        <criteriaItems>
            <field>ASI_MFM_Payment__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>JP Payment Read-Only</value>
        </criteriaItems>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
    </rules>
    <rules>
        <fullName>ASI_MFM_KR_CashOutFVNotice</fullName>
        <actions>
            <name>ASI_MFM_KR_CashOutFVNotice</name>
            <type>Alert</type>
        </actions>
        <active>true</active>
        <formula>CONTAINS( RecordType.DeveloperName, &apos;ASI_MFM_KR&apos;) &amp;&amp; ASI_MFM_Finance_Verify_LineNumber__c ==  ASI_MFM_CN_SYS_Count_Payment_Line_Items__c &amp;&amp;  ASI_MFM_Cash_Out_Payment__c &amp;&amp; ASI_MFM_CN_SYS_Count_Payment_Line_Items__c &gt; 0</formula>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
    </rules>
    <rules>
        <fullName>ASI_MFM_KR_CashOut_Offset_SetVATAmt</fullName>
        <actions>
            <name>ASI_MFM_KR_CashOut_Offset_SetVATAmt</name>
            <type>FieldUpdate</type>
        </actions>
        <active>true</active>
        <booleanFilter>1 AND ( 2 OR 3)</booleanFilter>
        <criteriaItems>
            <field>ASI_MFM_Payment__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>KR Payment,KR Payment Read-Only</value>
        </criteriaItems>
        <criteriaItems>
            <field>ASI_MFM_Payment__c.ASI_MFM_Cash_Out_Payment__c</field>
            <operation>equals</operation>
            <value>True</value>
        </criteriaItems>
        <criteriaItems>
            <field>ASI_MFM_Payment__c.ASI_MFM_Offset_Payment__c</field>
            <operation>equals</operation>
            <value>True</value>
        </criteriaItems>
        <triggerType>onAllChanges</triggerType>
    </rules>
    <rules>
        <fullName>ASI_MFM_KR_Free_Payment</fullName>
        <actions>
            <name>ASI_MFM_KR_Set_Payment_Standard</name>
            <type>FieldUpdate</type>
        </actions>
        <active>true</active>
        <criteriaItems>
            <field>ASI_MFM_Payment__c.ASI_MFM_Status__c</field>
            <operation>equals</operation>
            <value>Draft</value>
        </criteriaItems>
        <criteriaItems>
            <field>ASI_MFM_Payment__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>KR Payment Read-Only</value>
        </criteriaItems>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
    </rules>
    <rules>
        <fullName>ASI_MFM_KR_Set_Payment_Read-Only</fullName>
        <actions>
            <name>ASI_MFM_KR_Set_Payment_Read_Only</name>
            <type>FieldUpdate</type>
        </actions>
        <active>false</active>
        <formula>ISPICKVAL(ASI_MFM_Status__c, &quot;Approved&quot;) &amp;&amp;  OR(ISPICKVAL(PRIORVALUE( ASI_MFM_Status__c ), &quot;Draft&quot;),ISPICKVAL(PRIORVALUE( ASI_MFM_Status__c ), &quot;Submitted&quot;))  &amp;&amp; ( CONTAINS(RecordType.DeveloperName, &quot;ASI_MFM_KR_Payment&quot;))</formula>
        <triggerType>onAllChanges</triggerType>
    </rules>
    <rules>
        <fullName>ASI_MFM_MY_Finalize_Payment</fullName>
        <actions>
            <name>ASI_MFM_MY_Set_Payment_Read_Only</name>
            <type>FieldUpdate</type>
        </actions>
        <active>true</active>
        <criteriaItems>
            <field>ASI_MFM_Payment__c.ASI_MFM_Status__c</field>
            <operation>equals</operation>
            <value>Submitted,Final,Complete</value>
        </criteriaItems>
        <criteriaItems>
            <field>ASI_MFM_Payment__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>MY Payment</value>
        </criteriaItems>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
    </rules>
    <rules>
        <fullName>ASI_MFM_MY_Free_Payment</fullName>
        <actions>
            <name>ASI_MFM_MY_Set_Payment_Standard</name>
            <type>FieldUpdate</type>
        </actions>
        <active>true</active>
        <criteriaItems>
            <field>ASI_MFM_Payment__c.ASI_MFM_Status__c</field>
            <operation>equals</operation>
            <value>Draft</value>
        </criteriaItems>
        <criteriaItems>
            <field>ASI_MFM_Payment__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>MY Payment Read-Only</value>
        </criteriaItems>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
    </rules>
    <rules>
        <fullName>ASI_MFM_PH_DF_Free_Payment</fullName>
        <actions>
            <name>ASI_MFM_PH_DF_Set_Payment_Standard</name>
            <type>FieldUpdate</type>
        </actions>
        <active>true</active>
        <criteriaItems>
            <field>ASI_MFM_Payment__c.ASI_MFM_Status__c</field>
            <operation>equals</operation>
            <value>Draft</value>
        </criteriaItems>
        <criteriaItems>
            <field>ASI_MFM_Payment__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>PH DF Payment Read-Only</value>
        </criteriaItems>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
    </rules>
    <rules>
        <fullName>ASI_MFM_PH_DF_Set_Payment_Read-Only</fullName>
        <actions>
            <name>ASI_MFM_PH_DF_Set_Payment_Read_Only</name>
            <type>FieldUpdate</type>
        </actions>
        <active>true</active>
        <formula>ISPICKVAL(ASI_MFM_Status__c, &quot;Final&quot;) &amp;&amp; ISPICKVAL(PRIORVALUE( ASI_MFM_Status__c ), &quot;Submitted&quot;) &amp;&amp; ( CONTAINS(RecordType.DeveloperName, &quot;ASI_MFM_PH_DF_Payment&quot;))</formula>
        <triggerType>onAllChanges</triggerType>
    </rules>
    <rules>
        <fullName>ASI_MFM_PH_DP_Free_Payment</fullName>
        <actions>
            <name>ASI_MFM_PH_DP_Set_Payment_Standard</name>
            <type>FieldUpdate</type>
        </actions>
        <active>true</active>
        <criteriaItems>
            <field>ASI_MFM_Payment__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>PH DP Payment Read-Only</value>
        </criteriaItems>
        <criteriaItems>
            <field>ASI_MFM_Payment__c.ASI_MFM_Status__c</field>
            <operation>equals</operation>
            <value>Draft</value>
        </criteriaItems>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
    </rules>
    <rules>
        <fullName>ASI_MFM_PH_DP_Set_Payment_Read-Only</fullName>
        <actions>
            <name>ASI_MFM_PH_DP_Set_Payment_Read_Only</name>
            <type>FieldUpdate</type>
        </actions>
        <active>true</active>
        <formula>ISPICKVAL(ASI_MFM_Status__c, &quot;Final&quot;) &amp;&amp; ISPICKVAL(PRIORVALUE( ASI_MFM_Status__c ), &quot;Submitted&quot;) &amp;&amp; ( CONTAINS(RecordType.DeveloperName, &quot;ASI_MFM_PH_DP_Payment&quot;))</formula>
        <triggerType>onAllChanges</triggerType>
    </rules>
    <rules>
        <fullName>ASI_MFM_SG_ETL_Date</fullName>
        <actions>
            <name>ASI_MFM_Set_SG_ETL_Date</name>
            <type>FieldUpdate</type>
        </actions>
        <active>true</active>
        <criteriaItems>
            <field>ASI_MFM_Payment__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>SG Payment,SG Payment Read-Only</value>
        </criteriaItems>
        <criteriaItems>
            <field>ASI_MFM_Payment__c.ASI_MFM_ETL__c</field>
            <operation>equals</operation>
            <value>True</value>
        </criteriaItems>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
    </rules>
    <rules>
        <fullName>ASI_MFM_SG_Finalize_Payment</fullName>
        <actions>
            <name>ASI_MFM_SG_Set_Payment_Read_Only</name>
            <type>FieldUpdate</type>
        </actions>
        <active>true</active>
        <criteriaItems>
            <field>ASI_MFM_Payment__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>SG Payment</value>
        </criteriaItems>
        <criteriaItems>
            <field>ASI_MFM_Payment__c.ASI_MFM_Status__c</field>
            <operation>equals</operation>
            <value>Submitted,Final,Complete</value>
        </criteriaItems>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
    </rules>
    <rules>
        <fullName>ASI_MFM_SG_Payment_Rejected_Email_Alert</fullName>
        <actions>
            <name>ASI_MFM_SG_Payment_Rejected_Email_Alert</name>
            <type>Alert</type>
        </actions>
        <active>true</active>
        <formula>ISPICKVAL(ASI_MFM_Status__c, &quot;Draft&quot;) &amp;&amp; ISPICKVAL(PRIORVALUE( ASI_MFM_Status__c ), &quot;Submitted&quot;) &amp;&amp; ( CONTAINS(RecordType.DeveloperName, &quot;ASI_MFM_SG&quot;))</formula>
        <triggerType>onAllChanges</triggerType>
    </rules>
    <rules>
        <fullName>ASI_MFM_Send_Payment_Rejection_Notification_Email</fullName>
        <actions>
            <name>ASI_MFM_Payment_Rejection_Notification_Email_Alert</name>
            <type>Alert</type>
        </actions>
        <active>true</active>
        <formula>ISPICKVAL(ASI_MFM_Status__c, &quot;Draft&quot;) &amp;&amp; ISPICKVAL(PRIORVALUE( ASI_MFM_Status__c ), &quot;Submitted&quot;) &amp;&amp; (  CONTAINS(RecordType.DeveloperName, &quot;ASI_MFM_TW&quot;))</formula>
        <triggerType>onAllChanges</triggerType>
    </rules>
    <rules>
        <fullName>ASI_MFM_Set_Payment_Ext_ID</fullName>
        <actions>
            <name>ASI_MFM_Set_Payment_External_ID</name>
            <type>FieldUpdate</type>
        </actions>
        <active>true</active>
        <booleanFilter>1 AND (2 AND 3)</booleanFilter>
        <criteriaItems>
            <field>ASI_MFM_Payment__c.Name</field>
            <operation>notEqual</operation>
        </criteriaItems>
        <criteriaItems>
            <field>ASI_MFM_Payment__c.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>CAP Payment,CAP Payment Read-Only,OPEX SG Payment,OPEX SG Payment Read-Only,KR Payment,KR Payment Read-Only,GF Payment,GF Payment Read-Only,CAP T&amp;E Payment</value>
        </criteriaItems>
        <criteriaItems>
            <field>ASI_MFM_Payment__c.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>OPEX HK Payment,OPEX HK Payment Read-Only,OPEX TH Payment,OPEX TH Payment Read-Only,HK Payment,HK Payment Read-Only</value>
        </criteriaItems>
        <triggerType>onAllChanges</triggerType>
    </rules>
    <rules>
        <fullName>ASI_MFM_TH_ETL_Date</fullName>
        <actions>
            <name>ASI_MFM_Set_TH_ETL_Date</name>
            <type>FieldUpdate</type>
        </actions>
        <active>true</active>
        <criteriaItems>
            <field>ASI_MFM_Payment__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>TH Payment,TH Payment Read-Only</value>
        </criteriaItems>
        <criteriaItems>
            <field>ASI_MFM_Payment__c.ASI_MFM_ETL__c</field>
            <operation>equals</operation>
            <value>True</value>
        </criteriaItems>
        <description>Set ETL date</description>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
    </rules>
    <rules>
        <fullName>ASI_MFM_TH_Finalize_Payment</fullName>
        <actions>
            <name>ASI_MFM_TH_Set_Payment_Read_Only</name>
            <type>FieldUpdate</type>
        </actions>
        <active>true</active>
        <criteriaItems>
            <field>ASI_MFM_Payment__c.ASI_MFM_Status__c</field>
            <operation>equals</operation>
            <value>Submitted,Final,Complete</value>
        </criteriaItems>
        <criteriaItems>
            <field>ASI_MFM_Payment__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>TH Payment</value>
        </criteriaItems>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
    </rules>
    <rules>
        <fullName>ASI_MFM_TH_Free_Payment</fullName>
        <actions>
            <name>ASI_MFM_TH_Set_Payment_Standard</name>
            <type>FieldUpdate</type>
        </actions>
        <active>true</active>
        <criteriaItems>
            <field>ASI_MFM_Payment__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>TH Payment Read-Only</value>
        </criteriaItems>
        <criteriaItems>
            <field>ASI_MFM_Payment__c.ASI_MFM_Status__c</field>
            <operation>equals</operation>
            <value>Draft</value>
        </criteriaItems>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
    </rules>
    <rules>
        <fullName>ASI_MFM_TH_Payment_Rejected_Email_Alert</fullName>
        <actions>
            <name>ASI_MFM_TH_Payment_Rejected_Email_Alert</name>
            <type>Alert</type>
        </actions>
        <active>true</active>
        <formula>ISPICKVAL(ASI_MFM_Status__c, &quot;Draft&quot;) &amp;&amp; ISPICKVAL(PRIORVALUE( ASI_MFM_Status__c ), &quot;Submitted&quot;) &amp;&amp; ( CONTAINS(RecordType.DeveloperName, &quot;ASI_MFM_TH&quot;))</formula>
        <triggerType>onAllChanges</triggerType>
    </rules>
    <rules>
        <fullName>ASI_MFM_TW_Payment_Complete_Notification</fullName>
        <actions>
            <name>ASI_MFM_TW_Payment_Complete_Notification</name>
            <type>Alert</type>
        </actions>
        <active>true</active>
        <criteriaItems>
            <field>ASI_MFM_Payment__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>TW Payment,TW Payment Read-Only</value>
        </criteriaItems>
        <criteriaItems>
            <field>ASI_MFM_Payment__c.ASI_MFM_Status__c</field>
            <operation>equals</operation>
            <value>Complete</value>
        </criteriaItems>
        <description>Send email notification to Payment owner when payment status is updated to “Complete”</description>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
    </rules>
    <rules>
        <fullName>ASI_MFM_Uncheck_ETL_Flag</fullName>
        <actions>
            <name>ASI_MFM_Uncheck_ETL_Flag</name>
            <type>FieldUpdate</type>
        </actions>
        <active>true</active>
        <formula>ISPICKVAL( ASI_MFM_Status__c , &quot;Draft&quot;) &amp;&amp; ISPICKVAL( PRIORVALUE( ASI_MFM_Status__c ), &quot;Final&quot;)</formula>
        <triggerType>onAllChanges</triggerType>
    </rules>
</Workflow>
